### ISSUE TITLE
Beta7 Tooling installer window ends up nearly off the screen.

### ISSUE THREAD

**Issue by burtonrodman** [aspnet/Tooling#168] opened 2015-09-03 13:33 UTC
When the Beta7 Tooling installer completed, its window was pushed nearly off of the screen.  Only the right edge including the X button were visible in the upper left corner of my screen.

**Comment by sayedihashimi** [comment] 2015-09-29 21:29
TFS:149356
I've added it to our TFS bug tracker, will reply back here soon.

**Comment by joeloff** [comment] 2015-09-29 21:40
Pretty sure this is a known issue that we cannot control as its managed by the installer service in the OS. I'll dig up the old bug we've had on this,

**Comment by joeloff** [comment] 2015-09-29 21:44
Found it: 1204887

UI rendering of the MSI is under control of the OS installer service. Below is a link about the dialog table.

This is by design: Excerpt from https://msdn.microsoft.com/en-us/library/aa368286(v=vs.85).aspx 

*The integer values for width and height are in the Installer Units, not dialog units.

The two centering values are ignored for subsequent dialog boxes in a wizard sequence. Dialog box positions are set by the user or as for the previous dialog box. These dialog box sequences are created by a NewDialog ControlEvent.*

**Comment by barrytang** [comment] 2015-10-06 20:57
This will be addressed by ASP.NET RC since we will be shipping a chainer which will have a custom UI.

**Closed by barrytang** 2015-10-06 20:57 UTC
Labels: TFS Tracked
