### ISSUE TITLE
Visual studio - npm shows wrong status

### ISSUE THREAD

**Issue by qwert789** [aspnet/Tooling#514] opened 2016-05-21 08:54 UTC
After installation of ASP.NET Core RC2, npm shows wrong status - "npm - not installed" although all dependencies was successfully installed/ resolved:
![npmdependenices](https://cloud.githubusercontent.com/assets/1618071/15447394/d7a9dac6-1f49-11e6-91e7-0883d2f42a8c.PNG)

PATH=C:\Program Files\nodejs;C:\Program Files\Git\cmd;.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
"C:\Program Files\nodejs\npm.CMD" install
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN prefer global node-gyp@3.3.1 should be installed with -g
> node-sass@3.7.0 install C:\Projects\Sample\Sample.Web\node_modules\node-sass
> node scripts/install.js
Binary downloaded and installed at C:\Projects\Sample\Sample.Web\node_modules\node-sass\vendor\win32-x64-48\binding.node
> node-sass@3.7.0 postinstall C:\Projects\Sample\Sample.Web\node_modules\node-sass
> node scripts/build.js
"C:\Projects\Sample\Sample.Web\node_modules\node-sass\vendor\win32-x64-48\binding.node" exists. 
 testing binary.
Binary is fine; exiting.
Sample@1.0.0 C:\Projects\Sample\Sample.Web
+-- browser-sync@2.12.8 
| +-- browser-sync-client@2.4.2 
| | +-- etag@1.7.0 
| | `-- fresh@0.3.0 
| +-- browser-sync-ui@0.5.19 
| | +-- async-each-series@0.1.1 
| | +-- connect-history-api-fallback@1.2.0 
| | +-- stream-throttle@0.1.3 
| | | +-- commander@2.9.0 
| | | `-- limiter@1.1.0 
| | `-- weinre@2.0.0-pre-I0Z7U9OV 
| |   +-- express@2.5.11 
| |   | +-- connect@1.9.2 
| |   | | `-- formidable@1.0.17 
| |   | +-- mime@1.2.4 
| |   | +-- mkdirp@0.3.0 
| |   | `-- qs@0.4.2 
| |   +-- nopt@3.0.6 
| |   | `-- abbrev@1.0.7 
| |   `-- underscore@1.7.0 
| +-- bs-recipes@1.2.2 
| +-- chokidar@1.4.3 
| | +-- anymatch@1.3.0 
| | +-- async-each@1.0.0 
| | +-- glob-parent@2.0.0 
| | +-- inherits@2.0.1 
| | +-- is-binary-path@1.0.1 
| | | `-- binary-extensions@1.4.0 
| | +-- is-glob@2.0.1 
| | +-- path-is-absolute@1.0.0 
| | `-- readdirp@2.0.0 
| +-- connect@3.4.1 
| | +-- debug@2.2.0 
| | | `-- ms@0.7.1 
| | +-- finalhandler@0.4.1 
| | | +-- on-finished@2.3.0 
| | | | `-- ee-first@1.1.1 
| | | `-- unpipe@1.0.0 
| | +-- parseurl@1.3.1 
| | `-- utils-merge@1.0.0 
| +-- dev-ip@1.0.1 
| +-- easy-extender@2.3.2 
| | `-- lodash@3.10.1 
| +-- eazy-logger@2.1.3 
| | +-- lodash.clonedeep@4.3.1 
| | | `-- lodash._baseclone@4.5.7 
| | +-- opt-merger@1.1.1 
| | | `-- lodash@3.10.1 
| | `-- tfunk@3.0.2 
| |   `-- object-path@0.9.2 
| +-- emitter-steward@1.0.0 
| +-- fs-extra@0.26.7 
| | +-- jsonfile@2.3.1 
| | `-- klaw@1.2.0 
| +-- http-proxy@1.13.2 
| | +-- eventemitter3@1.2.0 
| | `-- requires-port@1.0.0 
| +-- immutable@3.7.6 
| +-- localtunnel@1.8.1 
| | +-- openurl@1.1.0 
| | +-- request@2.65.0 
| | | +-- aws-sign2@0.6.0 
| | | +-- bl@1.0.3 
| | | | `-- readable-stream@2.0.6 
| | | +-- caseless@0.11.0 
| | | +-- combined-stream@1.0.5 
| | | | `-- delayed-stream@1.0.0 
| | | +-- extend@3.0.0 
| | | +-- forever-agent@0.6.1 
| | | +-- form-data@1.0.0-rc4 
| | | | `-- async@1.5.2 
| | | +-- har-validator@2.0.6 
| | | | `-- is-my-json-valid@2.13.1 
| | | |   +-- generate-function@2.0.0 
| | | |   +-- generate-object-property@1.2.0 
| | | |   | `-- is-property@1.0.2 
| | | |   `-- jsonpointer@2.0.0 
| | | +-- hawk@3.1.3 
| | | | +-- boom@2.10.1 
| | | | +-- cryptiles@2.0.5 
| | | | +-- hoek@2.16.3 
| | | | `-- sntp@1.0.9 
| | | +-- http-signature@0.11.0 
| | | | +-- asn1@0.1.11 
| | | | +-- assert-plus@0.1.5 
| | | | `-- ctype@0.5.3 
| | | +-- isstream@0.1.2 
| | | +-- json-stringify-safe@5.0.1 
| | | +-- node-uuid@1.4.7 
| | | +-- oauth-sign@0.8.2 
| | | +-- qs@5.2.0 
| | | +-- stringstream@0.0.5 
| | | +-- tough-cookie@2.2.2 
| | | `-- tunnel-agent@0.4.3 
| | `-- yargs@3.29.0 
| |   +-- camelcase@1.2.1 
| |   `-- window-size@0.1.4 
| +-- lodash@4.10.0 
| +-- micromatch@2.3.7 
| | +-- arr-diff@2.0.0 
| | | `-- arr-flatten@1.0.1 
| | +-- array-unique@0.2.1 
| | +-- braces@1.8.4 
| | | +-- expand-range@1.8.2 
| | | | `-- fill-range@2.2.3 
| | | |   +-- is-number@2.1.0 
| | | |   +-- randomatic@1.1.5 
| | | |   `-- repeat-string@1.5.4 
| | | +-- preserve@0.2.0 
| | | `-- repeat-element@1.1.2 
| | +-- expand-brackets@0.1.5 
| | | `-- is-posix-bracket@0.1.1 
| | +-- extglob@0.3.2 
| | +-- filename-regex@2.0.0 
| | +-- is-extglob@1.0.0 
| | +-- kind-of@3.0.3 
| | | `-- is-buffer@1.1.3 
| | +-- normalize-path@2.0.1 
| | +-- object.omit@2.0.0 
| | | +-- for-own@0.1.4 
| | | | `-- for-in@0.1.5 
| | | `-- is-extendable@0.1.1 
| | +-- parse-glob@3.0.4 
| | | +-- glob-base@0.3.0 
| | | `-- is-dotfile@1.0.2 
| | `-- regex-cache@0.4.3 
| |   +-- is-equal-shallow@0.1.3 
| |   `-- is-primitive@2.0.0 
| +-- opn@3.0.3 
| +-- portscanner@1.0.0 
| | `-- async@0.1.15 
| +-- qs@6.1.0 
| +-- resp-modifier@6.0.1 
| | `-- minimatch@2.0.10 
| |   `-- brace-expansion@1.1.4 
| |     +-- balanced-match@0.4.1 
| |     `-- concat-map@0.0.1 
| +-- serve-index@1.7.3 
| | +-- accepts@1.2.13 
| | | `-- negotiator@0.5.3 
| | +-- batch@0.5.3 
| | +-- escape-html@1.0.3 
| | +-- http-errors@1.3.1 
| | | `-- statuses@1.3.0 
| | `-- mime-types@2.1.11 
| |   `-- mime-db@1.23.0 
| +-- serve-static@1.10.2 
| | `-- send@0.13.1 
| |   +-- depd@1.1.0 
| |   +-- destroy@1.0.4 
| |   +-- mime@1.3.4 
| |   +-- range-parser@1.0.3 
| |   `-- statuses@1.2.1 
| +-- socket.io@1.4.5 
| | +-- engine.io@1.6.8 
| | | +-- accepts@1.1.4 
| | | | +-- mime-types@2.0.14 
| | | | | `-- mime-db@1.12.0 
| | | | `-- negotiator@0.4.9 
| | | +-- base64id@0.1.0 
| | | +-- engine.io-parser@1.2.4 
| | | | +-- after@0.8.1 
| | | | +-- arraybuffer.slice@0.0.6 
| | | | +-- base64-arraybuffer@0.1.2 
| | | | +-- blob@0.0.4 
| | | | +-- has-binary@0.1.6 
| | | | | `-- isarray@0.0.1 
| | | | `-- utf8@2.1.0 
| | | `-- ws@1.0.1 
| | |   +-- options@0.0.6 
| | |   `-- ultron@1.0.2 
| | +-- has-binary@0.1.7 
| | | `-- isarray@0.0.1 
| | +-- socket.io-adapter@0.4.0 
| | | `-- socket.io-parser@2.2.2 
| | |   +-- debug@0.7.4 
| | |   +-- isarray@0.0.1 
| | |   `-- json3@3.2.6 
| | +-- socket.io-client@1.4.5 
| | | +-- backo2@1.0.2 
| | | +-- component-bind@1.0.0 
| | | +-- component-emitter@1.2.0 
| | | +-- engine.io-client@1.6.8 
| | | | +-- component-inherit@0.0.3 
| | | | +-- has-cors@1.1.0 
| | | | +-- parsejson@0.0.1 
| | | | +-- parseqs@0.0.2 
| | | | +-- xmlhttprequest-ssl@1.5.1 
| | | | `-- yeast@0.1.2 
| | | +-- indexof@0.0.1 
| | | +-- object-component@0.0.3 
| | | +-- parseuri@0.0.4 
| | | | `-- better-assert@1.0.2 
| | | |   `-- callsite@1.0.0 
| | | `-- to-array@0.1.4 
| | `-- socket.io-parser@2.2.6 
| |   +-- benchmark@1.0.0 
| |   +-- component-emitter@1.1.2 
| |   +-- isarray@0.0.1 
| |   `-- json3@3.3.2 
| +-- ua-parser-js@0.7.10 
| +-- ucfirst@1.0.0 
| `-- yargs@4.4.0 
|   +-- camelcase@2.1.1 
|   +-- cliui@3.2.0 
|   | `-- wrap-ansi@2.0.0 
|   +-- decamelize@1.2.0 
|   +-- lodash.assign@4.0.9 
|   | +-- lodash.keys@4.0.7 
|   | `-- lodash.rest@4.0.3 
|   +-- os-locale@1.4.0 
|   | `-- lcid@1.0.0 
|   |   `-- invert-kv@1.0.0 
|   +-- pkg-conf@1.1.2 
|   | +-- find-up@1.1.2 
|   | | `-- path-exists@2.1.0 
|   | +-- load-json-file@1.1.0 
|   | | `-- parse-json@2.2.0 
|   | |   `-- error-ex@1.3.0 
|   | |     `-- is-arrayish@0.2.1 
|   | `-- symbol@0.2.2 
|   +-- read-pkg-up@1.0.1 
|   | `-- read-pkg@1.1.0 
|   |   `-- path-type@1.1.0 
|   +-- require-main-filename@1.0.1 
|   +-- string-width@1.0.1 
|   | +-- code-point-at@1.0.0 
|   | | `-- number-is-nan@1.0.0 
|   | `-- is-fullwidth-code-point@1.0.0 
|   +-- window-size@0.2.0 
|   +-- y18n@3.2.1 
|   `-- yargs-parser@2.4.0 
|     `-- camelcase@2.1.1 
+-- del@2.2.0 
| +-- globby@4.1.0 
| | +-- array-union@1.0.1 
| | +-- arrify@1.0.1 
| | `-- glob@6.0.4 
| +-- is-path-cwd@1.0.0 
| +-- is-path-in-cwd@1.0.0 
| | `-- is-path-inside@1.0.0 
| |   `-- path-is-inside@1.0.1 
| +-- object-assign@4.1.0 
| +-- pify@2.3.0 
| `-- pinkie-promise@2.0.1 
|   `-- pinkie@2.0.4 
+-- gulp@3.9.1 
| +-- archy@1.0.0 
| +-- chalk@1.1.3 
| | +-- ansi-styles@2.2.1 
| | +-- escape-string-regexp@1.0.5 
| | +-- has-ansi@2.0.0 
| | | `-- ansi-regex@2.0.0 
| | +-- strip-ansi@3.0.1 
| | `-- supports-color@2.0.0 
| +-- deprecated@0.0.1 
| +-- interpret@1.0.1 
| +-- liftoff@2.2.1 
| | +-- extend@2.0.1 
| | +-- findup-sync@0.3.0 
| | | `-- glob@5.0.15 
| | +-- flagged-respawn@0.3.2 
| | +-- rechoir@0.6.2 
| | `-- resolve@1.1.7 
| +-- minimist@1.2.0 
| +-- orchestrator@0.3.7 
| | +-- end-of-stream@0.1.5 
| | +-- sequencify@0.0.7 
| | `-- stream-consume@0.1.0 
| +-- pretty-hrtime@1.0.2 
| +-- semver@4.3.6 
| +-- tildify@1.2.0 
| | `-- os-homedir@1.0.1 
| +-- v8flags@2.0.11 
| | `-- user-home@1.1.1 
| `-- vinyl-fs@0.3.14 
|   +-- defaults@1.0.3 
|   +-- glob-stream@3.1.18 
|   | +-- glob@4.5.3 
|   | +-- glob2base@0.0.12 
|   | | `-- find-index@0.1.1 
|   | +-- ordered-read-streams@0.1.0 
|   | +-- through2@0.6.5 
|   | | `-- readable-stream@1.0.34 
|   | |   `-- isarray@0.0.1 
|   | `-- unique-stream@1.0.0 
|   +-- glob-watcher@0.0.6 
|   | `-- gaze@0.5.2 
|   |   `-- globule@0.1.0 
|   |     +-- glob@3.1.21 
|   |     | +-- graceful-fs@1.2.3 
|   |     | `-- inherits@1.0.2 
|   |     +-- lodash@1.0.2 
|   |     `-- minimatch@0.2.14 
|   +-- graceful-fs@3.0.8 
|   +-- mkdirp@0.5.1 
|   | `-- minimist@0.0.8 
|   +-- strip-bom@1.0.0 
|   | `-- first-chunk-stream@1.0.0 
|   +-- through2@0.6.5 
|   | `-- readable-stream@1.0.34 
|   |   `-- isarray@0.0.1 
|   `-- vinyl@0.4.6 
|     `-- clone@0.2.0 
+-- gulp-angular-templatecache@1.8.0 
| +-- event-stream@3.3.2 
| | +-- duplexer@0.1.1 
| | +-- from@0.1.3 
| | +-- map-stream@0.1.0 
| | +-- pause-stream@0.0.11 
| | +-- split@0.3.3 
| | +-- stream-combiner@0.0.4 
| | `-- through@2.3.8 
| +-- gulp-footer@1.0.5 
| +-- gulp-header@1.8.2 
| +-- js-string-escape@1.0.1 
| `-- path@0.12.7 
|   +-- process@0.11.3 
|   `-- util@0.10.3 
+-- gulp-clean-css@2.0.7 
| +-- clean-css@3.4.12 
| | +-- commander@2.8.1 
| | | `-- graceful-readlink@1.0.1 
| | `-- source-map@0.4.4 
| |   `-- amdefine@1.0.0 
| +-- readable-stream@2.1.4 
| | +-- buffer-shims@1.0.0 
| | +-- core-util-is@1.0.2 
| | +-- isarray@1.0.0 
| | +-- process-nextick-args@1.0.7 
| | +-- string_decoder@0.10.31 
| | `-- util-deprecate@1.0.2 
| +-- vinyl-bufferstream@1.0.1 
| | `-- bufferstreams@1.0.1 
| |   `-- readable-stream@1.1.14 
| |     `-- isarray@0.0.1 
| `-- vinyl-sourcemaps-apply@0.2.1 
|   `-- source-map@0.5.6 
+-- gulp-concat@2.6.0 
| +-- concat-with-sourcemaps@1.0.4 
| `-- through2@0.6.5 
|   +-- readable-stream@1.0.34 
|   | `-- isarray@0.0.1 
|   `-- xtend@4.0.1 
+-- gulp-sass@2.3.1 
| +-- node-sass@3.7.0 
| | +-- async-foreach@0.1.3 
| | +-- cross-spawn-async@2.2.4 
| | | +-- lru-cache@4.0.1 
| | | | +-- pseudomap@1.0.2 
| | | | `-- yallist@2.0.0 
| | | `-- which@1.2.9 
| | |   `-- isexe@1.1.2 
| | +-- gaze@1.0.0 
| | | `-- globule@0.2.0 
| | |   +-- glob@3.2.11 
| | |   | `-- minimatch@0.3.0 
| | |   +-- lodash@2.4.2 
| | |   `-- minimatch@0.2.14 
| | +-- get-stdin@4.0.1 
| | +-- in-publish@2.0.0 
| | +-- meow@3.7.0 
| | | +-- camelcase-keys@2.1.0 
| | | | `-- camelcase@2.1.1 
| | | +-- loud-rejection@1.3.0 
| | | | +-- array-find-index@1.0.1 
| | | | `-- signal-exit@2.1.2 
| | | +-- map-obj@1.0.1 
| | | +-- normalize-package-data@2.3.5 
| | | | +-- hosted-git-info@2.1.5 
| | | | +-- is-builtin-module@1.0.0 
| | | | | `-- builtin-modules@1.1.1 
| | | | `-- validate-npm-package-license@3.0.1 
| | | |   +-- spdx-correct@1.0.2 
| | | |   | `-- spdx-license-ids@1.2.1 
| | | |   `-- spdx-expression-parse@1.0.2 
| | | |     `-- spdx-exceptions@1.0.4 
| | | +-- redent@1.0.0 
| | | | +-- indent-string@2.1.0 
| | | | | `-- repeating@2.0.1 
| | | | |   `-- is-finite@1.0.1 
| | | | `-- strip-indent@1.0.1 
| | | `-- trim-newlines@1.0.0 
| | +-- mkdirp@0.5.1 
| | | `-- minimist@0.0.8 
| | +-- nan@2.3.3 
| | +-- node-gyp@3.3.1 
| | | +-- fstream@1.0.9 
| | | | `-- mkdirp@0.5.1 
| | | |   `-- minimist@0.0.8 
| | | +-- glob@4.5.3 
| | | | `-- minimatch@2.0.10 
| | | +-- minimatch@1.0.0 
| | | | +-- lru-cache@2.7.3 
| | | | `-- sigmund@1.0.1 
| | | +-- mkdirp@0.5.1 
| | | | `-- minimist@0.0.8 
| | | +-- npmlog@2.0.4 
| | | | +-- ansi@0.3.1 
| | | | +-- are-we-there-yet@1.1.2 
| | | | | `-- delegates@1.0.0 
| | | | `-- gauge@1.2.7 
| | | |   +-- has-unicode@2.0.0 
| | | |   +-- lodash.pad@4.4.0 
| | | |   | +-- lodash._baseslice@4.0.0 
| | | |   | +-- lodash._basetostring@4.12.0 
| | | |   | `-- lodash.tostring@4.1.3 
| | | |   +-- lodash.padend@4.5.0 
| | | |   | `-- lodash._basetostring@4.12.0 
| | | |   `-- lodash.padstart@4.5.0 
| | | |     `-- lodash._basetostring@4.12.0 
| | | +-- osenv@0.1.3 
| | | | `-- os-tmpdir@1.0.1 
| | | +-- path-array@1.0.1 
| | | | `-- array-index@1.0.0 
| | | |   `-- es6-symbol@3.0.2 
| | | |     +-- d@0.1.1 
| | | |     `-- es5-ext@0.10.11 
| | | |       `-- es6-iterator@2.0.0 
| | | +-- semver@5.1.0 
| | | `-- tar@2.2.1 
| | |   `-- block-stream@0.0.9 
| | `-- sass-graph@2.1.1 
| |   +-- glob@6.0.4 
| |   `-- yargs@3.32.0 
| |     `-- camelcase@2.1.1 
| `-- through2@2.0.1 
|   `-- readable-stream@2.0.6 
+-- gulp-sourcemaps@1.6.0 
| +-- convert-source-map@1.2.0 
| +-- graceful-fs@4.1.4 
| +-- strip-bom@2.0.0 
| | `-- is-utf8@0.2.1 
| `-- vinyl@1.1.1 
|   +-- clone@1.0.2 
|   `-- clone-stats@0.0.1 
+-- gulp-uglify@1.5.3 
| +-- deap@1.0.0 
| +-- fancy-log@1.2.0 
| | `-- time-stamp@1.0.1 
| +-- isobject@2.1.0 
| +-- uglify-js@2.6.2 
| | +-- async@0.2.10 
| | +-- uglify-to-browserify@1.0.2 
| | `-- yargs@3.10.0 
| |   +-- cliui@2.1.0 
| |   | +-- center-align@0.1.3 
| |   | | +-- align-text@0.1.4 
| |   | | | `-- longest@1.0.1 
| |   | | `-- lazy-cache@1.0.4 
| |   | +-- right-align@0.1.3 
| |   | `-- wordwrap@0.0.2 
| |   `-- window-size@0.1.0 
| `-- uglify-save-license@0.4.1 
+-- gulp-util@3.0.7 
| +-- array-differ@1.0.0 
| +-- array-uniq@1.0.2 
| +-- beeper@1.1.0 
| +-- dateformat@1.0.12 
| +-- gulplog@1.0.0 
| | `-- glogg@1.0.0 
| +-- has-gulplog@0.1.0 
| | `-- sparkles@1.0.0 
| +-- lodash._reescape@3.0.0 
| +-- lodash._reevaluate@3.0.0 
| +-- lodash._reinterpolate@3.0.0 
| +-- lodash.template@3.6.2 
| | +-- lodash._basecopy@3.0.1 
| | +-- lodash._basetostring@3.0.1 
| | +-- lodash._basevalues@3.0.0 
| | +-- lodash._isiterateecall@3.0.9 
| | +-- lodash.escape@3.2.0 
| | | `-- lodash._root@3.0.1 
| | +-- lodash.keys@3.1.2 
| | | +-- lodash._getnative@3.9.1 
| | | +-- lodash.isarguments@3.0.8 
| | | `-- lodash.isarray@3.0.4 
| | +-- lodash.restparam@3.6.1 
| | `-- lodash.templatesettings@3.1.1 
| +-- multipipe@0.1.2 
| | `-- duplexer2@0.0.2 
| |   `-- readable-stream@1.1.14 
| |     `-- isarray@0.0.1 
| +-- object-assign@3.0.0 
| +-- replace-ext@0.0.1 
| `-- vinyl@0.5.3 
`-- rimraf@2.5.2 
  `-- glob@7.0.3 
    +-- inflight@1.0.5 
    | `-- wrappy@1.0.2 
    `-- once@1.3.3 
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12

**Comment by YaoaY** [comment] 2016-05-21 10:02
fsevents

**Comment by Kukkimonsuta** [comment] 2016-05-21 12:57
Probably duplicate with https://github.com/aspnet/Tooling/issues/479

**Comment by sayedihashimi** [comment] 2016-05-24 16:23
Closing as a dupe of #479. If it's not a dupe please add details.

**Closed by sayedihashimi** 2016-05-24 16:23 UTC
