### ISSUE TITLE
warning in cshtml for <a> taghelper with target attribute

### ISSUE THREAD

**Issue by wjzhou** [aspnet/Tooling#831] opened 2016-10-25 18:28 UTC
The visual studio show a warning when using <a> taghelper with target attribute.

```
<a target="_blank" asp-action="...">
```

The warning description is: 
Attribute is allowed only when 'href' is present.

**Comment by mlorbetske** [comment] 2016-12-22 00:22
cc @madskristensen

**Comment by cihadsevim** [comment] 2017-07-09 17:31
Stilll going on.

**Comment by NTaylorMullen** [comment] 2017-07-10 17:06
Duplicate of: https://github.com/aspnet/Razor/issues/1428

**Closed by NTaylorMullen** 2017-07-10 17:06 UTC
Labels: duplicate
