### ISSUE TITLE
Adding files or folders is slow with DNX/DNC projects

### ISSUE THREAD

**Issue by ciel** [aspnet/Tooling#450] opened 2016-04-12 20:22 UTC
At the moment, with the dnx tooling at `1.0.0-rc2-20221`, once you've run `dotnet restore` on a solution or project of any considerable size, if you attempt to go to any area and right click and select `Add...`, the menu can oftentimes be very slow to pull up. 

Additionally, adding new folders frequently causes Visual Studio to crash for me; At least on this computer. I've tested all of this with a fresh install of Windows 10 x64, Visual Studio 2015 Professional with Update 2, updated Web Tooling, the newest dot net cli, and all of the DNX versions updated to their highest available.

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002349)

Product Information:
 Version:     1.0.0-rc2-002349
 Commit Sha:  ed9309b90b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

`dnvm list` output:

```
Active Version           Runtime Architecture OperatingSystem Alias
------ -------           ------- ------------ --------------- -----
       1.0.0-beta8       clr     x64          win
       1.0.0-beta8       clr     x86          win
       1.0.0-beta8       coreclr x64          win
       1.0.0-beta8       coreclr x86          win
       1.0.0-rc1-update1 clr     x64          win
       1.0.0-rc1-update1 clr     x86          win
       1.0.0-rc1-update1 coreclr x64          win
       1.0.0-rc1-update1 coreclr x86          win
       1.0.0-rc1-update2 clr     x64          win
       1.0.0-rc1-update2 clr     x86          win
       1.0.0-rc1-update2 coreclr x64          win
       1.0.0-rc1-update2 coreclr x86          win
       1.0.0-rc2-20221   clr     x64          win             default
       1.0.0-rc2-20221   clr     x86          win
  *    1.0.0-rc2-20221   coreclr x64          win             latest
       1.0.0-rc2-20221   coreclr x86          win
```

`dnvm` output:

```
   ___  _  ___   ____  ___
  / _ \/ |/ / | / /  |/  /
 / // /    /| |/ / /|_/ /
/____/_/|_/ |___/_/  /_/
.NET Version Manager v1.0.0-rc2-15546
By Microsoft Open Technologies, Inc.
usage: dnvm <command> [<arguments...>]

Current feed settings:
Default Stable: https://www.nuget.org/api/v2
Default Unstable: https://www.myget.org/F/aspnetvnext/api/v2
Current Stable Override: <none>
Current Unstable Override: <none>
```

`Visual Studio 2015` info:

```
Microsoft Visual Studio Professional 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Professional

LightSwitch for Visual Studio 2015   00322-40000-00000-AA341
Microsoft LightSwitch for Visual Studio 2015

Visual Basic 2015   00322-40000-00000-AA341
Microsoft Visual Basic 2015

Visual C# 2015   00322-40000-00000-AA341
Microsoft Visual C# 2015

Visual C++ 2015   00322-40000-00000-AA341
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   5.2.60328.3
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.20203.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.7.1   14.0.11112.0
Azure App Service Tools v2.7.1

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.4.2
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.0.168
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60311.1
Microsoft SQL Server Data Tools

TypeScript   1.8.30.0
TypeScript tools for Visual Studio
```

**Comment by ciel** [comment] 2016-04-13 21:42
This seems to have become progressively worse with the newest `dotnet cli` build (`1.0.0-rc2-002376`)

I'm willing to try and make a video to demonstrate the problem if it would help; As it stands, Visual Studio is growing maddeningly unusable. The delay was bearable, but now it begins to crash and force-close when trying to get to the **Add** slide-out. 

To be clear, I'm referring to this menu, not the dialog that appears once you're able to click it. The dialog itself seems to behave fine and presents no trouble. It is the transition from the standard context menu to the add pop-out when you hover/click **Add**.

![add slide-out context menu](http://i.xomf.com/cqhfy.jpg)

**Comment by sayedihashimi** [comment] 2016-04-13 22:15
@ciel if you can show that we have regressed performance when updating dotnet cli or going from dnx -> dotnet we would be very interested in that. I think we would investigate that right away. Could you do the video? Then I can share internally so that we can figure out what's happening.

**Comment by ciel** [comment] 2016-04-15 15:01
Alright. [Here is a video](https://drive.google.com/open?id=0B7spg3aCB00dTlpZMnFHbjVJdXM) demonstrating, from start to finish, how that menu gets progressively slower and less reliable as you do `dotnet restore`. 

The packages being used in this video are listed here. 

`*.Core, *.data.Raven, *.Identity, *.data.Lore` all use;
````
    "Microsoft.NETCore.App": "1.0.0-rc2-3002306",
    "Newtonsoft.Json": "8.0.3",
    "RavenDB.Client": "3.0.30120-Unstable"
````
*.web.Api also uses ...
````

    "Microsoft.AspNetCore.Identity": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-*",
    "Microsoft.AspNetCore.Routing": "1.0.0-*",
    "Microsoft.AspNetCore.Hosting": "1.0.0-*",
    "Microsoft.AspNetCore.Cors": "1.0.0-*",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-*",
    "Microsoft.AspNetCore.Antiforgery": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.Google": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.OAuth": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0-*",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-*",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-*",
    "Microsoft.Extensions.DependencyInjection": "1.0.0-*",
    "Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0-*",
    "Microsoft.Extensions.Logging": "1.0.0-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-*",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-*",
    "Autofac": "4.0.0-rc1-177",
    "Autofac.Extensions.DependencyInjection": "4.0.0-rc1-177"
````

**Comment by sayedihashimi** [comment] 2016-04-15 17:11
@ciel thanks. I've added this to our internal TFS, we will reply back here soon.

TFS: 213414

**Comment by sayedihashimi** [comment] 2016-04-15 17:19
@ciel just watched your video. I think the issue is that VS doesn't support dotnet yet. We are working on that and it will be included in the RC2 release. Have you noticed any slowness with dnx in your version of VS?

**Comment by ciel** [comment] 2016-04-15 18:02
I'm not sure what you mean. I don't use DNX. I've been told by multiple sources not to use anything related to DNX - the only reason to install it is to slightly update the tooling in Visual Studio.

**Comment by abpiskunov** [comment] 2016-04-16 18:34
Just tried with latest  tooling and dotnet. Tried same thing you did in the video for Nuget.Core solution which has 54 projects. It doe snot repro. 

You probably have something else. I don't even see how restore could make that context menu slower and we would need your help to investigate that. Could you repeat steps you did in the video with your solution and take a snapshot with "perfview" for the moment where you try to access context menu?

**Comment by ciel** [comment] 2016-04-16 21:01
Yeah, I'll absolutely give it a try. I'm completely willing to agree it might be something on my machine locally - but I tried it with a fresh install of Windows 10, so I'm unsure what it could be. Give me a bit to figure out how to use this perfview thing and I'll get back to you.

**Comment by ciel** [comment] 2016-04-16 21:08
Is there some special way I need to run perfview to get the data you need? Or do I just set `devenv.exe` as the target to get a memory dump and click it at the same time I try to open the menu?

**Comment by ciel** [comment] 2016-04-16 21:19
And when I say I "don't use DNX" - I mean that the only reason it is on my computer is because I've been told it is what allows Visual Studio to recognize the new FTMs (partially) so it at least attempts to cooperate with programs using them. I'm not actively using any projects that are executing on a dnx framework, and I'm not using any dnx commands from the command line.

**Comment by ciel** [comment] 2016-04-16 21:44
In talking with @davidfowl, we're pretty certain this is a problem with build `1.0.0-rc2-20221` and how it affects the tooling in Visual Studio - so it's pretty likely that it will be resolved when new tooling ships and DNX is dropped completely.

Removing `1.0.0-rc2-20221` and going back to `1.0.0-rc1-update2` resolves the problem as well - even though doing that means Visual Studio now fails to understand the `netstandard`, `netcore`, and `net451` FTM dependencies and won't give any information/intellisense on them.

**Comment by abpiskunov** [comment] 2016-04-16 22:22
@davidfowl  could you comment please with your thoughts about how 1.0.0-rc2-20221   affects tooling?

**Comment by davidfowl** [comment] 2016-04-16 23:05
The latest DNX has bad nuget compatibility rules so it generates the wrong lock file.

**Comment by ciel** [comment] 2016-04-16 23:54
I'm not using the Visual Studio nuget restore feature; all of my restores are done using `dotnet restore` on the command line.

**Comment by davidfowl** [comment] 2016-04-16 23:55
Yea it shouldn't affect the slowness of adding files. That's just a project system issue.

**Comment by ciel** [comment] 2016-04-16 23:55
It has nothing to do with the project. I can reproduce this in any project; Mine and others.

**Comment by sayedihashimi** [comment] 2017-01-06 21:04
Sorry for the delay here. There has been a lot of changes that have happened since you filled this issue. Can you try again with VS2017 RC and let us know if this issue persists? I'll close this now, but please reopen if it's still an issue.

**Closed by sayedihashimi** 2017-01-06 21:04 UTC
Labels: TFS Tracked
