### ISSUE TITLE
XML doc does not get copied from referenced projects

### ISSUE THREAD

**Issue by Inkp** [aspnet/Tooling#745] opened 2016-08-24 08:43 UTC
When referencing class-library (csproj) which generating XML doc from xproj-based project said XML doc does not get copied to output folder.
Repo demonstrating this issue https://github.com/Inkp/aspnet-tooling-bug
SampleClassLibrary is generating XML doc. But it is nowhere to be found in output folder of SampleCoreConsole.

**Comment by mlorbetske** [comment] 2016-08-26 07:14
I've been told this will be fixed with the upcoming move to csproj project files. Opening a bug in our internal database to track.

**Comment by mlorbetske** [comment] 2016-08-26 07:14
TFS Bug#257226

**Comment by balachir** [comment] 2017-03-01 23:56
Thanks for your feedback. I am unable to reproduce this issue with either the VS 2015 .NET Core tooling or the .NET Core tooling that ships in VS 2017. If you can still reproduce with VS 2017, please go ahead and re-activate or open a new issue. Thanks!

**Closed by balachir** 2017-03-01 23:56 UTC
Labels: TFS Tracked
