### ISSUE TITLE
dnu restore hangs

### ISSUE THREAD

**Issue by JorritSalverda** [aspnet/Tooling#440] opened 2016-04-04 13:13 UTC
When running the following commands on my build agent the dnu restore often hangs

```
> rm -rf /var/go/.dnx/packages
> dnu restore --no-cache

```

It hangs on different packages each run. Recreating the agent usually helps, but isn't much of a way to work. It can even happen the first time it runs, so doesn't seem to be caused by lingering files.

The build machine is a debian jessie docker container running coreclr version 1.0.0-rc1-update1. It's a single core machine on Google Cloud.

Could this perhaps be caused by a race condition? A deadlock?

**Comment by sayedihashimi** [comment] 2016-04-08 17:46
@JorritSalverda I'm not able to reproduce this.

Also we are moving from `dnu` to `dotnet`. Have you had a chance to try this with `dotnet`? If it works for `dotnet` then I think we are good.

**Comment by mikes-gh** [comment] 2016-04-15 14:33
I see also this with dnu (have to close vstudio) but never with dotnet restore so I guess we wont have to worry about this

**Comment by sayedihashimi** [comment] 2016-04-26 18:15
@mikes-gh thanks. I'm hoping that this issue doesn't repro with `dotnet`. I'll close this now. If you run into this problem with `dotnet` please file an issue at https://github.com/dotnet/cli.

**Closed** 2016-05-05 17:08 UTC
