### ISSUE TITLE
Console Application (Package) project template dependencies are not alphabetized

### ISSUE THREAD

**Issue by olegsych** [aspnet/Tooling#56] opened 2015-05-05 16:25 UTC
- Create a new _Console Application (Package)_ project in Visual Studio 2015 RC.
- Notice that dependencies in `project.json` are not alphabetized (see related #55)
```json
"dnxcore50" : {
  "dependencies": {
    "System.Console": "4.0.0-beta-22816",
    "System.Collections": "4.0.10-beta-22816",
    "System.Linq": "4.0.0-beta-22816",
    "System.Threading": "4.0.10-beta-22816",
    "Microsoft.CSharp": "4.0.0-beta-22816"
  }
}
```

**Comment by Eilon** [comment] 2015-05-05 18:00
@rustd

**Comment by rustd** [comment] 2015-07-21 19:17
Duplicate of aspnet/Tooling#57

**Closed by rustd** 2015-07-21 19:17 UTC
Labels: templates
