### ISSUE TITLE
Test runner should pick up environment variables from launchSettings.json

### ISSUE THREAD

**Issue by Eilon** [aspnet/Tooling#456] opened 2016-04-28 16:48 UTC
This has been reported a couple of times in other repos:
* https://github.com/aspnet/Mvc/issues/4230
* https://github.com/aspnet/Testing/issues/202

And it seems like it would be quite useful, as environment variables are important for a lot of code to run correctly, and thus important in testing scenarios.

cc @vijayrkn @BillHiebert

**Comment by sayedihashimi** [comment] 2016-05-05 16:41
TFS: 219219
I've added this to our internal TFS, we will reply back here soon.

**Comment by gzak** [comment] 2016-06-14 17:10
@sayedihashimi any updates?

**Comment by barrytang** [comment] 2016-06-16 20:49
We won't be fixing this for VS2015 and the next version of VS will have a different experience.

**Closed by barrytang** 2016-06-16 20:49 UTC
Labels: TFS Tracked

**Comment by senwen** [comment] 2016-06-22 23:08
Just got bit by this. @barrytang, what do you suggest as the workaround for VS2015? Our team relies on unit tests working properly as part of our CI/CD process and the idea of hard coding environment values in our unit tests or loading and managing environment values from another source is not ideal.

**Comment by arielcloud** [comment] 2016-12-18 21:27
Is it fixed on VS 2017? how can I use environment variables on integration tests? thanks!

**Comment by sthomas1978** [comment] 2017-01-27 15:53
I have exactly the same problem. Dont know whether this helps but when I create a a test server I do the following

`            var config = new ConfigurationBuilder()
                .AddCommandLine(new[] {"--environment=Development"})
                .Build();
            var server = new TestServer(new WebHostBuilder()
                .UseConfiguration(config)
                .UseStartup<Startup>());

`
This lets me inject the environment I am using via the command line. It seems to work for me

**Comment by eswann** [comment] 2017-05-01 04:35
Is this fixed? The test framework isn't picking up environment variables for me.  This should be reopened.

**Comment by justin-lavelle** [comment] 2017-05-18 17:53
Also for me this does not seem to be working.

Microsoft Visual Studio Professional 2017
Version 15.2 (26430.4) Release

The environment variables in launchSettings.json are not available in the EnvironmentVariablesConfigurationProvider .

**Comment by edward93** [comment] 2017-07-11 12:39
@sthomas1978 your solution didn't work for me. I suspect  via --environment parameter you cannot pass your env var anymore

**Comment by richturner** [comment] 2017-10-03 09:22
Why is this issue (and duplicates) closed?

This is a fundamental problem that setting the environment variables in a test project should be available in the tests, only thing for this at the moment seems to be to parse the launchSettings.json file and pass the environment variables into the ConfigurationBuilder

**Comment by GiuseppePiscopo** [comment] 2017-11-13 11:02
Looking at [this commit](https://github.com/azabluda/dotConnectOracle/commit/b9022ee32e9475ef113129a1726b137980d79e0f) in dotConnectOracle project, there's a workaround in [this SO answer](https://stackoverflow.com/questions/43927955/should-getenvironmentvariable-work-in-xunit-test/43951218#43951218)

**Comment by koertner** [comment] 2018-02-15 20:57
I have also been trying to get the specific EnvironmentVariable depending on the profile I am running (as you can do in an Web.MVC applicaiton) and have had no success.  I looked at the dotConnectOracle but this is pulling in all the profiles which doesn't help because I want to know which is the currently active profile.  

I looked at the ASPNETCORE_ENVIRONMENT variable that is contained in the ConfigurationBuilder when running the tests and it does not match any of my ASPNETCORE_ENVIRONMENT variables I have set so I cant tell what is setting it.

If there is a way to read the commandLineArgs before the test runs start that would also work.
I am using Xunit 2.3.1 in .net Core 2.0.

Is there any way to work around this issue?

**Comment by barrytang** [comment] 2018-02-19 22:06
To report new issues, use the [Report a Problem](https://developercommunity.visualstudio.com/) tool. The GitHub Issue Tracker for the aspnet/Tooling repo is now deprecated in favor of the Report a Problem tool.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.

**Comment by Felixking** [comment] 2019-02-27 15:44
I'm not sure this ever got resolved. In this [issue](https://github.com/aspnet/Mvc/issues/4230), which was closed because this issue was opened, says:

> I tried setting the `Hosting:Environment` environment variable to Development within the test's `.xproj` file, but when the test executes within VS, the environment still resolves to Production (which appears to be the default value for that property). How do I set environment variables for test projects?

This is the exact same problem I'm facing.

`WebHost.CreateDefaultBuilder();` produces a `hostingEnvironment` with EnvironmentName of Production, even though I have localhost specified in ASPNETCORE_ENVIRONMENT variable.

![image](https://user-images.githubusercontent.com/1824102/53502529-476a1100-3a7c-11e9-90df-739e8066dc43.png)
![image](https://user-images.githubusercontent.com/1824102/53502547-54870000-3a7c-11e9-966c-4dbafaaa118d.png)

What is strange is I swear this worked before and is a recent regression.

**Comment by lmcarreiro** [comment] 2019-03-03 15:39
@barrytang you said that it would not be fixed in VS 2015, but it is not working in VS 2017 either. Shouldn't this issue be reopen?

**Comment by barrytang** [comment] 2019-03-06 01:12
Please do and please use the Report a Problem too. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us?view=vs-2017) for more details. Thanks!
