### ISSUE TITLE
VS 2017 RC ".." Folder when using TargetFramework netcoreapp1.1

### ISSUE THREAD

**Issue by jonnybi** [aspnet/Tooling#963] opened 2017-01-20 15:28 UTC
Everything works fine except having these .. folders in my projects.
I have vs 2015 and 2017 RC installed.

![screenie](https://cloud.githubusercontent.com/assets/19321660/22154721/ebcf75e4-df2c-11e6-8d82-7bafda3d404f.png)

Here is my test solution
[MyTestApp.zip](https://github.com/aspnet/Tooling/files/719736/MyTestApp.zip)

Installed:
Microsoft .NET Core 1.0.1 - VS 2015 Tooling Preview 2
Microsoft .NET Core 1.1.0 - SDK 1.0.0 Preview 2.1-003177 (x64)

**Comment by scottaddie** [comment] 2017-01-20 20:59
@mlorbetske Can you confirm that this is a duplicate of https://github.com/aspnet/Tooling/issues/935?

**Comment by mlorbetske** [comment] 2017-01-20 22:04
Yep, it's a duplicated of #935, this is fixed in the next release of Visual Studio 2017

**Closed by mlorbetske** 2017-01-20 22:04 UTC

**Comment by jonnybi** [comment] 2017-01-21 17:27
Sry i didn't find that one
