### ISSUE TITLE
incorrect file dependencies inside solution explorer after crash

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#257] opened 2015-11-01 16:08 UTC
Hi, I was moving some ts files from approot to wwwroot and suddendly vs crashed. after the restart opening that in the folder the ts file is placed as dependent from html, instead at the same level.

![error](https://cloud.githubusercontent.com/assets/127777/10869822/facf829a-80ba-11e5-99e4-9408e1fe5026.png)

**Comment by sayedihashimi** [comment] 2015-11-01 16:15
Thanks Luca, can you reproduce this bug? If so could you give some specific steps we can follow?

**Comment by lucamorelli** [comment] 2015-11-01 16:26
This version (rc) unfortunately crashes quite often, and I don't know if this is the reason of this behavior. reopening the project doesn't help, I cannot drag the ts file in another directory, but I copy and paste it in another directory: coyping the **app.ts** file in the **home** dir, the ts files appears in the right position, but if I grab it again in the **app** directory is placed under the html file.
I don't find anything in the xproj file: I'm preparing a copy of everything and sending via dropbox if you like

**Comment by BillHiebert** [comment] 2015-11-02 20:00
@lucamorelli  Can you get a dump file or callstack containing the crash?

**Comment by lucamorelli** [comment] 2015-11-02 21:19
I can't reproduce this crash

**Comment by lucamorelli** [comment] 2015-11-02 21:28
btw: how can I start the registration of the dump file on the fly when Vs crashes?

**Comment by sayedihashimi** [comment] 2015-11-09 18:58
@abpiskunov @BillHiebert @balachir  do you know how to get a dump when VS crashes?

**Comment by abpiskunov** [comment] 2015-11-09 19:12
When it is crashing, there will be a dialog offering to debug it. Debug and open in new vs instance. Then in Debug menu choose save a dump file etc

**Comment by abpiskunov** [comment] 2015-11-09 19:22
Btw, placing ts file under html is expected behavior for current nesting rules (based on the same file name), there is also a css file ubder html in your pucture. Unfortunatelly these nesting rules are not configurable at the moment.

**Comment by sayedihashimi** [comment] 2015-12-17 22:32
Closing this now since we were not able to get a dump

**Closed by sayedihashimi** 2015-12-17 22:32 UTC
