### ISSUE TITLE
VS 2017 RC: The prerelease has expired

### ISSUE THREAD

**Issue by gimlichael** [aspnet/Tooling#957] opened 2017-01-18 11:34 UTC
Dear sir or madam

What the frack?!

I have a MSDN subscription, but all the sudden, the VS 2017 RC has an expired license.
Pressing "Check for an updated license" gives back a "We could not unlock yada-yada-yada.

I am furious right now .. things like this, makes me not want to test RC ever again!

Please, release a patch ASAP that resolves this issue or open up for unlocking an updated license.

We cannot change the date/time backward in time, as others have suggested, due to this setting being managed by our organization.

**Comment by EuroForm** [comment] 2017-01-18 12:24
Unfortunately I have the very same problem. We have 1 dev in our team without this issue and 2 devs with this issue.

As you mention, there is a hack (changing time) that is working for us who can actually modify this on our PC. This is not a fix, but we did manage to find a "somewhat working" temporary workaround using following:
1) On visual studio prompt (initial load or every 30 min or so for me), do following
2) Adjust time 1 week back (if not working, set 1 month back, if not working, set 1 year back)
3) Click "Check for an updated license" (requires login)
4) Close popup (and use Visual Studio)
5) Adjust time automatically (=set to current time) so you can browse HTTPS/SSL in browser
6) Wait for popup and repeat process (I get prompted every 30 minute or so)

I know above is far from a fix - just trying to help out other people in desperate need of using their development environment.

Please fix this ASAP. If need be, disable all license control for a few days until you have this under control again.

Thanks for understanding.

**Comment by rs38** [comment] 2017-01-18 13:35
these time based workarounds do not work on my machine (non domain-based)

**Comment by doenersoldat** [comment] 2017-01-18 13:39
The time based workarounds do also not work to machines in enterprise enviroument (Changing Machines Date ist restricted in active cirectory policy!).

**Comment by OutSorcerer** [comment] 2017-01-18 14:26
Although I see "Some settings are managed by your organization" in new Windows 10 UI and cannot change time there I am still able to change it via old UI from Control Panel and use the workaroud above. Could help someone.

**Comment by MattJeanes** [comment] 2017-01-18 14:29
See [VS Developer Community](https://developercommunity.visualstudio.com/content/problem/11860/license-expired-visual-studio-2017-rc.html) for a workaround using Fiddler faking the activation response, should work for everyone as long as you have local admin

**Comment by fjdumont** [comment] 2017-01-18 14:55
Same here.

For those trying to change the local date/time: AD policy is just being enforced by using the "Change date" UI from Windows itself. However, you can use a local CMD prompt (with elevated privileges, which I guess you have being a developer): `date 2016-01-01` should do the trick.

**Comment by MattJeanes** [comment] 2017-01-18 21:29
Update from Christoph Berlin (see above link):

'Hi everyone, thanks so much for the quick feedback. We identified the root cause of this temporary issue and a fix has been deployed on the backend. Your Visual Studio RC build will work as expected - there are no steps necessary for users.'

**Comment by davkean** [comment] 2017-02-02 23:16
Folks, we apologise for the issue, this has been resolved.

**Closed by davkean** 2017-02-02 23:16 UTC
