### ISSUE TITLE
Visual Studio crashes when renaming a constructor argument used in a base(arg) call

### ISSUE THREAD

**Issue by ericwj** [aspnet/Tooling#308] opened 2015-11-26 06:08 UTC
Reproduce by standing on `arg` in the `Derived` class in the code below, pressing F2 to rename and then starting to type e.g. `log` or `name`. The crash will occur on the second character of the new name.

Reproduce also by going to the end of the name after pressing F2 and pressing backspace until there are two characters left. Visual Studio crashes when you then press Backspace again.

```C#
namespace Namespace
{
	public class Base {
		public Base(string arg) { }
	}
	public class Derived : Base {
		public Derived(string arg) : base(arg) { }
	}
}
```

**Comment by MartinJohns** [comment] 2015-11-28 14:46
I tried to reproduce this behavior, but I can't. Perhaps you should add some more information, like used Visual Studio version and project type.  
I'm using Visual Studio 2015 Community Edition with the Update 1 RC (14.0.24627.00) and tried it in a classic console application project targeting .NET 4.6.1.

**Comment by ericwj** [comment] 2015-11-29 20:18
Ah, this is a DNX project. rc1-final. I had it in a Class Library then reproduced in a Console App. I'm also not using Update 1 RC. I'll try installing that on another box and see if this problem reproduces there.

**Comment by ericwj** [comment] 2015-11-30 10:14
It didn't happen on clean install VS15COM Update 1 RC. I can tell you the debugger will break and report an error in `Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action<System.Exception>)`. I've seen `Microsoft.CodeAnalysis.Workspaces.dll` appearing. If I continue after that, it'll report `ExecutionEngineException` before VS closes. But perhaps you knew that from the crash dump I uploaded from VS Feedback.

That'll point at least in the right direction. Might it be something fixed in Update 1? If so, no point in investigating further. I was thinking maybe attaching a debugger and getting symbols would work, but I didn't seem to get any starting at `Microsoft.CodeAnalysis.Workspaces.dll` from the Microsoft Symbol Servers.

**Comment by sayedihashimi** [comment] 2015-12-17 22:24
TFS: 174129
I've added this to our internal TFS, we will reply back here soon.

**Comment by dpoeschl** [comment] 2016-01-23 01:25
FYI: I'm looking into this from the Roslyn side, but so far I'm unable to get the crash on VS 2015 Update 1 + AspNet5 RC1 Update 1 (`ASP.NET and Web Tools 2015 (RC1 Update 1) 14.1.11120.0`). 

As a side note, you will see something like "1 unresolvable conflict" and "Rename will update 3 references in 2 files"  -- these are due to https://github.com/dotnet/roslyn/issues/3351, which we're also working on.

**Comment by dpoeschl** [comment] 2016-01-23 01:38
But it does definitely crash on VS2015 RTM + AspNet5. Thanks for the bug report @ericwj!

This had been previously filed as https://github.com/dotnet/roslyn/issues/5035 and we did fix it in Roslyn in VS 2015 Update 1.

@sayedihashimi I've resolved the internal bug, and we should be able to close this issue now.

**Comment by sayedihashimi** [comment] 2016-02-02 18:46
Based on @dpoeschl comments I'll close this now.

**Closed by sayedihashimi** 2016-02-02 18:46 UTC
Labels: TFS Tracked
