### ISSUE TITLE
new project wizard error (cannot find the file specified)

### ISSUE THREAD

**Issue by OneCyrus** [aspnet/Tooling#487] opened 2016-05-17 10:16 UTC
while creating a new "ASP.NET Core Web Application (.NET Core/.NET Framework)" and any template (empty, Web API,  Web Application) i get the following error:

![image](https://cloud.githubusercontent.com/assets/7747800/15318910/9356d212-1c28-11e6-899d-282f88151ec1.png)

any idea to troubleshoot? dotnet CLI works fine.

**Comment by YehudahA** [comment] 2016-05-17 13:27
+1

**Comment by sayedihashimi** [comment] 2016-05-18 17:17
TFS: 223022
I've added this to our internal TFS, we will reply back here soon.

**Comment by balachir** [comment] 2016-05-19 18:39
We suspect you might be running into a setup issue. Can you share your Add/Remove Programs (ARP) and Help-About? We'd like to check if the components installed properly. 

Search for 'core' in ARP and it should show:
![image](https://cloud.githubusercontent.com/assets/8246794/15405277/0f4a0e78-1db6-11e6-8e63-2f319deed788.png)

VS Help-About should show .NET Core Tools (Preview1) and ASP.NET and Web Tools 2015.1

![image](https://cloud.githubusercontent.com/assets/8246794/15405299/2ab8142a-1db6-11e6-8456-be8c058b2629.png)

Also, the Extensions folder should have the right dlls installed

![image](https://cloud.githubusercontent.com/assets/8246794/15405338/495dcd3e-1db6-11e6-9a71-9a41150f36a3.png)

**Comment by YehudahA** [comment] 2016-05-19 19:02
In VS>Help>About I don't have Microsoft .NET Core Tools.

**Comment by OneCyrus** [comment] 2016-05-19 19:15
just found out that there was still something from rc1 installed. just uninstalled this (and the rc2 tools as well). installed the preview1 again. but still the same issue.

![image](https://cloud.githubusercontent.com/assets/7747800/15406000/bfbb5c0a-1e04-11e6-8433-13b1089e4a8f.png)

i'm missing the core tools (that's probably the issue):

![image](https://cloud.githubusercontent.com/assets/7747800/15406273/23a8d64c-1e06-11e6-8acc-f5fd83b69072.png)
![image](https://cloud.githubusercontent.com/assets/7747800/15406279/2c4f63ba-1e06-11e6-8356-908331ff13b9.png)
![image](https://cloud.githubusercontent.com/assets/7747800/15406312/4e10fa90-1e06-11e6-9a14-588fc42db5b6.png)

**Comment by balachir** [comment] 2016-05-19 21:14
@joeloff , can you take a look please?

**Comment by joeloff** [comment] 2016-05-19 21:46
@OneCyrus The RC1 remnant you showed was just the old DNX runtime packages, but it's fine to remove those manually.

From the screenshot you shared it does seem like all the files are installed.

Could you please do the following:

1. Open VS developer prompt and run devenv /log. This will create an ActivityLog.xml file in %localappdata%\Microsoft\VisualStudio\14.0
2. Could you please look in %temp% and grab all the logs from there that start with dd_DotNetCoreTools

Please attach the logs and the activity log to this issue.

**Comment by OneCyrus** [comment] 2016-05-19 22:40
ActivityLog.xml was in %APPDATA%\Microsoft\VisualStudio\14.0 in %LOCALAPPDATA% I couldn't find an ActivityLog.xml.

1. [ActivityLog.zip](https://github.com/aspnet/Tooling/files/273583/ActivityLog.zip)
2. [CoreToolsLogs.zip](https://github.com/aspnet/Tooling/files/273590/CoreToolsLogs.zip)

thanks, for looking into it!

**Comment by joeloff** [comment] 2016-05-19 23:30
Thanks. The ActivityLog.zip file has no files in it

**Comment by OneCyrus** [comment] 2016-05-20 08:27
oh sorry, try this one.
[ActivityLog.zip](https://github.com/aspnet/Tooling/files/274166/ActivityLog.zip)

**Comment by joeloff** [comment] 2016-05-20 15:12
Thanks @OneCyrus 

I do see some package failures, but the logs shows that the .NET Core Tools extension was loaded. The errors I'm seeing are for the VSGraphics package, Team Explorer and another extension under a random folder (this was likely installed by a pure VSIX)

When you open the Tools Menu, and then go to Extensions & Updates, do you see an entry like the one below

**Comment by OneCyrus** [comment] 2016-05-20 16:04
yes, it's there: 
![image](https://cloud.githubusercontent.com/assets/7747800/15434006/3985a4ea-1eb5-11e6-895f-5c211988061b.png)

**Comment by joeloff** [comment] 2016-05-20 16:06
Ok, that's good. Next thing to check. Is NuGet installed (it should show up in the Extensions & Updates menu). And if so, can you provide the version of NuGet that's present?

**Comment by OneCyrus** [comment] 2016-05-20 16:07
here it is:
![image](https://cloud.githubusercontent.com/assets/7747800/15434111/b012334e-1eb5-11e6-9263-fc26ad04f0ce.png)

**Comment by joeloff** [comment] 2016-05-20 18:00
That's a newer version than what shipped with Update 2. I just updated my VM to that version and I can still create projects. I just wanted to start ruling out anything that may play a part in this error.

Next question: Any errors reported in the EventViewer (eventvwr.msc) that coincide with the error. There might be something under the Windows Logs (Application or System logs).

**Comment by OneCyrus** [comment] 2016-05-20 18:17
no events to find when reproducing the error.

**Comment by stgeorgelorna** [comment] 2016-05-23 03:12
Having the exact same issue.  I've uninstalled and re-installed the core tools using the DotNet Core Tools preview a couple of times. Install completes successfully (or at least it says it does!)

I've attached the log files you mentioned above to see if they help for comparison.

No errors in the Event Viewer, but I did find an informational messaged in the Application log regarding the dev environment that occurred when I did the re-install. XML from that report also attached.
This same information message occurs with each install of the Dot net Core tools..

The version of the DotNet Core tools install I used is "DotNetCore.1.0.0.RC2-VS2015Tools.Preview1.exe" and the file version on that is: ‎1.0.20513.14

 Hopefully this will hep track down the issue!


[vs_perfdataerror.zip](https://github.com/aspnet/Tooling/files/276758/vs_perfdataerror.zip)
[dd_DotNetCoreTools.zip](https://github.com/aspnet/Tooling/files/276745/dd_DotNetCoreTools.zip)
[ActivityLog.zip](https://github.com/aspnet/Tooling/files/276748/ActivityLog.zip)

**Comment by joeloff** [comment] 2016-05-23 16:53
@stgeorgelorna Thank you for the logs. When you see the error, is it occuring after the VS wizard is launched (you're able to see the new project dialog and select Empty/Web API/Web Application), or does the error occur when you select the Web option in the File-->New Project dialog (you never see the Web Project dialog at all)?

**Comment by joeloff** [comment] 2016-05-24 17:01
I'm pretty sure we've narrowed it down to VS failing to find the Wizard DLL referenced by the templates. 
@stgeorgelorna, @OneCyrus would you mind running fuslogvw (you can launch if from a VS2015 developer command prompt) and then launch VS and go through the steps until you hit the error so we can see if there are any bind failures. Please attach the logs here if you can produce them.

**Comment by stgeorgelorna** [comment] 2016-05-24 18:32
Hello -- I've tried this and get no log files at all. Error still happens exactly as before, but no binding errors ever get created.

**Comment by OneCyrus** [comment] 2016-05-24 18:44
same here. fuslogvw doesn't show anything.

**Comment by joeloff** [comment] 2016-05-25 19:35
I've tracked down one instance where the errors everyone here are experiencing turned out to be related to NGEN images becoming out of sync. I'm hoping that's the case here as well. This was an internal issue that we saw on a developers machine. I'm not saying this is the cause, but the symptoms are similar.

The solution in that case was to close all instances of VS and regenerate the ngen cache (I think **ngen update** is what you need to run). You can run this from a VS 2015 Developer prompt

**Comment by OneCyrus** [comment] 2016-05-27 16:24
ngen update doesn't fix the problem here.

**Comment by romage** [comment] 2016-05-27 18:57
I'm getting the same issue. Ngen returns: 

C:\WINDOWS\system32>ngen update
Microsoft (R) CLR Native Image Generator - Version 4.6.1038.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Failed to load dependency Microsoft.Web.Configuration.AppHostFileProvider of assembly Microsoft.Web.Management, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 because of the following error : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
Failed to load dependency Microsoft.Web.Configuration.AppHostFileProvider of assembly Microsoft.Web.Management.Ftp, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 because of the following error : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
Failed to load dependency Microsoft.Web.Configuration.AppHostFileProvider of assembly Microsoft.Web.Management.Iis, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 because of the following error : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
Failed to load dependency System.Runtime.Loader of assembly Microsoft.CodeAnalysis.Scripting, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 because of the following error : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
Failed to load dependency System.Runtime.Loader of assembly Microsoft.CodeAnalysis.Scripting, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 because of the following error : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
Failed to load dependency System.Runtime.Loader of assembly Microsoft.CodeAnalysis.Scripting, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 because of the following error : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
All compilation targets are up to date.

**Comment by jramirezdev** [comment] 2016-06-06 03:08
Same error here, suggested solutions did not work on my end. Looking forward to seeing a fix.

**Comment by OneCyrus** [comment] 2016-06-10 20:59
still the same issue with the preview 2 nightly 6/7/16

**Comment by barrytang** [comment] 2016-06-20 17:38
Dupe of https://github.com/aspnet/Tooling/issues/515.

**Closed by barrytang** 2016-06-20 17:38 UTC
Labels: TFS Tracked

**Comment by MoaadGit** [comment] 2016-11-03 10:25
I have the same issue iam trying to create new asp.net core project and giving me same error

**Comment by frenklin** [comment] 2016-11-07 21:17
I had the same issue. Got the list of msi/exe from log file then ran them manually.

**Comment by OneBlueCubeDev** [comment] 2016-12-02 23:26
did anyone figure out the issue. I am getting the same error here as well

**Comment by jhaytaslim** [comment] 2017-06-05 07:49
Is this issue still not solved even with update3

**Comment by aalyassin** [comment] 2017-06-29 20:13
Even with Update 3 is not resolved yet. I have been trying all the suggestions above. Nothing seems to help. Last thing I tried was the ngen update.

**Comment by joeloff** [comment] 2017-06-29 20:20
Something else to try (to get a better error message). Create an empty solution, then right click on the solution and select Add, New Project and create a new ASP.NET Core project. Adding projects from the solutions sometimes provide more details in the error.
