### ISSUE TITLE
StarterWeb included jquery-validation and ...-unobtrusive.js but doesn't use them

### ISSUE THREAD

**Issue by madskristensen** [aspnet/Tooling#658] opened 2016-07-06 15:49 UTC
The default no-auth template includes 2 bower packages that is not being used. Those two packages should be removed

**Comment by mlorbetske** [comment] 2016-07-18 18:38
TFS Bug#241373

**Comment by mlorbetske** [comment] 2016-07-28 17:54
Duplicate of https://github.com/aspnet/Templates/issues/649

**Closed by mlorbetske** 2016-07-28 17:54 UTC
Labels: TFS Tracked
