### ISSUE TITLE
"Create directory for solution" places solution file in incorrect directory for ASP.NET 5 projects

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Tooling#126] opened 2015-08-02 01:21 UTC
I tried reporting this on Connect but kept getting errors so I'm reporting it here instead.
____

The "Create new directory for solution" option behaves differently for ASP.NET 5 projects compared to other project types. Given the following settings in the project creation dialog in Visual Studio:
 - Name: HelloWorld
 - Location: c:\Projects
 - Solution: Create new solution
 - Create directory for solution: Unticked

Creating a new ConsoleApplication will create HelloWorld.sln, HelloWorld.csproj and Program.cs in c:\Projects\HelloWorld. This is the expected behaviour.

However, when creating a blank ASP.NET 5 project, it will put the .sln file at c:\Projects\HelloWorld.sln. Additionally, when "Create new Git repository" or "Add to source control" are ticked, creation of the ASP.NET 5 project will add the entire parent directory (ie. c:\Projects) to source control, rather than just the new c:\Projects\HelloWorld directory.

**Comment by sayedihashimi** [comment] 2015-09-30 17:16
TFS:149638
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment] 2015-10-15 21:47
Hi @Daniel15 I chatted with the team and this is by design for ASP.NET 5. ASP.NET 5 is folder based and we use the solution root to place files like `global.json` and `nuget.config` for settings which apply across the solution.

I'll close this now since we are not planning any updates here.

**Closed by sayedihashimi** 2015-10-15 21:47 UTC
Labels: TFS Tracked
