### ISSUE TITLE
Upgrading to DotNet Core RC2 Preview seems to have broken Visual Studio

### ISSUE THREAD

**Issue by piotrpMSFT** [aspnet/Tooling#540] opened 2016-05-26 22:15 UTC
Let me start by saying that I'm receiving errors left and right inside Visual Studio since upgrading to the newest version of DotNet Core.  I'm going to just post one of the problems here in the hopes that they're all related and/or can be fixed the same.  I've tried uninstalling/repairing the packages here (https://www.microsoft.com/net/core#windows) several times, with no luck.

## Steps to reproduce
1. Create New Project
![image](https://cloud.githubusercontent.com/assets/3098820/15410884/4d686734-1dea-11e6-8837-dc542fdcf8bf.png)

2. Select Empty template
![image](https://cloud.githubusercontent.com/assets/3098820/15410889/58b0af20-1dea-11e6-9230-5f565f33be39.png)

3. Get the following error message:

![image](https://cloud.githubusercontent.com/assets/3098820/15410897/627d0102-1dea-11e6-90fd-bdf51528ef52.png)

## Environment data
`dotnet --info` output:

![image](https://cloud.githubusercontent.com/assets/3098820/15410936/98cb3148-1dea-11e6-9b84-14c777b7d587.png)

## Further issues

If it helps any, when I try to load a project from RC1, in the ActivityLog.xml file, I get an error loading ITelemetry or something like that.  I also get a failure file generated, which contains the following:

=====================
5/19/2016 5:24:26 PM
Recoverable
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ProjectSystem.DotNet.Publish.PublishLoader.<<Initialize>b__13_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.DotNet.Publish.PublishLoader.<Initialize>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.AutoLoadMethodStateMachine.<<StartExecution>b__6_0>d.MoveNext()
===================

I do not get this error when creating a new project, as I've done above.

**Comment by piotrpMSFT** [comment] 2016-05-26 22:16
Moving https://github.com/dotnet/cli/issues/3144 on behalf of @joshmouch

**Comment by sayedihashimi** [comment] 2016-05-26 23:06
TFS: 225780
I've added this to our internal TFS, we will reply back here soon.

**Comment by joeloff** [comment] 2016-05-26 23:36
Looking at one of the logs I got from @toddlucas there are some files, like the DNX.14.dll that shipped in RC1 that's getting marked as a shared component when RC1 is being removed when the MSI is upgraded. That implies that there's another MSI that's holding a reference count to the file.

We typically install the new product first before removing the old product during an upgrade. Anything that lives in both the old and new version would get a reference count of 2.

We'd need to track down the offending product. The logs only report the RC1 MSI.

**Comment by ctyar** [comment] 2016-05-29 18:01
I'm not sure its the same issue but after upgrading to the same version cant open aspnet/mvc repo solution anymore
after opening the solution this appers
![1](https://cloud.githubusercontent.com/assets/1432648/15635049/6ba94d60-25e9-11e6-8df7-be9e6514bc9d.png)
and then ...
![2](https://cloud.githubusercontent.com/assets/1432648/15635050/8771a79a-25e9-11e6-9094-c62b6f8ebbce.png)

ActivityLog.xml
[ActivityLog.zip](https://github.com/aspnet/Tooling/files/288463/ActivityLog.zip)

VsProjectFault_.failure
[VsProjectFault_320978f8-6f85-40a5-9115-332bac7e0aae.failure.zip](https://github.com/aspnet/Tooling/files/288467/VsProjectFault_320978f8-6f85-40a5-9115-332bac7e0aae.failure.zip)

I ran msiinv.exe but after 10 minutes I just canceled it.
turns out it was still working (5MB output). If u need this I can try again

**Comment by barrytang** [comment] 2016-06-20 17:35
Dupe of https://github.com/aspnet/Tooling/issues/515.

**Closed by barrytang** 2016-06-20 17:35 UTC
Labels: TFS Tracked
