### ISSUE TITLE
Add View dialog incosistent with Add New Item - View.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#344] opened 2015-12-18 17:12 UTC
If I do a right click on a Views folder and choose `Add View` I was presented with the following dialog:

![image](https://cloud.githubusercontent.com/assets/3386797/11902485/01ffe924-a591-11e5-8766-fc5952523fd5.png)

This dialog have a problem, it doesn't work if I want to create a standrad view (cshtml file) without a Model.

To create a new `.cshtml` as of right now, I have to right click Add New Item and then choose `MVC View Page`.

I think both actions should trigger the same dialog with options to create from model or empty.

**same happens with controllers and probably other things**

**Comment by sayedihashimi** [comment] 2015-12-18 19:01
@Bartmax the issue is that we do not yet have `Empty` and `Empty (without model)` as an option in the drop down. That's is a feature that we are working on for the next release (hopefully, not promises).

I think that @prafullbhosale has recently added the code for that.

**Comment by Bartmax** [comment] 2015-12-18 20:00
As far as you are aware of the issue is fine! ;) do I close the issue ?

**Comment by sayedihashimi** [comment] 2016-01-13 20:27
Closing

**Closed by sayedihashimi** 2016-01-13 20:27 UTC
