### ISSUE TITLE
Output Path appends Debug or Release to folder path

### ISSUE THREAD

**Issue by zemien** [aspnet/Tooling#383] opened 2016-01-24 21:30 UTC
I'm trying to control where the ASP .NET 5 RC1 output files go to. In regular projects, specifying "..\bin" for Debug configuration means output files end up in the bin folder, one level up. In ASP.NET 5 projects though, the output ends up in ..\bin\Debug or ..\bin\Release, even though I set "..\bin" as the .xproj OutputPath property for both configurations.

Is this a defect or by design (why?)? Is there a workaround? Thank you.

**Comment by davidfowl** [comment] 2016-01-24 21:39
xproj can have multiple outputs from a single build (per configuration).

**Comment by sayedihashimi** [comment] 2016-02-01 20:20
@BillHiebert if a user specifies the output path are we appending `$(Configuration)` to the specified path?

**Comment by sayedihashimi** [comment] 2016-02-19 17:33
Thanks for the report.
This is by design from the `dnx` command line. The `dnx` command line is getting replaced with `dotnet`. I think you'll find similar behavior in `dotnet`. If you try it and have feedback the correct repo for that is https://github.com/dotnet/cli. I'll close this now.

**Closed by sayedihashimi** 2016-02-19 17:33 UTC
