### ISSUE TITLE
BrowserLink Refresh closes iisexpress instead of refreshing the browser.

### ISSUE THREAD

**Issue by Northgates-Systems** [aspnet/Tooling#986] opened 2017-02-02 08:48 UTC
VS 2017 latest, Core 1.1

Repair vs2017 was getting stuck on Microsoft.AspNetCore.Debugger.JustInTime (or close to that).
Uninstalled vs 2017, restarted os, reinstalled vs 2017.

On any newly created core 1.1 (even some already existing projects).
1) start project without debugging
2) make a change in a cshtml file
3) click the Refresh BrowserLink

The changed document gets saved but iisExpress gets terminated.

**Comment by mlorbetske** [comment] 2017-02-02 14:52
TFS Bug#378597

**Comment by jodavis** [comment] 2017-02-09 18:30
This regression was caused by a workaround we had to add to RC.3 if VS2017 to avoid a very common deadlock hang. The hang and the regression have been fixed in the most recent update to VS2017 (2/7)

**Closed by jodavis** 2017-02-09 18:30 UTC
Labels: TFS Tracked
