### ISSUE TITLE
.bowerrc appears in project even though it doesn't exist

### ISSUE THREAD

**Issue by alanpurple** [aspnet/Tooling#870] opened 2016-11-19 12:14 UTC
I have to delete that ghost file every time I open the project

VS 2017 RC Enterprise, ASP.NET core web application, empty project

**Comment by lski** [comment] 2016-11-27 14:12
Also seen in VS2017 RC Community same project type

**Comment by scottaddie** [comment] 2016-12-08 02:56
This problem also occurs with the Web API project template in VS 2017 RC Enterprise.

**Comment by mlorbetske** [comment] 2016-12-21 23:17
This should be fixed for new projects in the most recent update to VS 2017 RC. Unfortunately, these changes don't automatically apply to existing projects (as the particular version of the msbuild files that define these behaviors is now pulled in directly in the project).

In the update, new projects get created using an attribute on the Project element called `Sdk` that uses the latest targets. This eliminates the need for the top and bottom imports normally found in the project file as well as the `PackageReference` for Microsoft.NET.Sdk.Web and the two globbing patterns for C# files and resx files.

**Comment by mlorbetske** [comment] 2016-12-21 23:19
You can see an example of what the changes look like in #915. Closing this one as the issue is fixed, we can continue discussion over at #915 if needed.

**Closed by mlorbetske** 2016-12-21 23:19 UTC
