### ISSUE TITLE
Merge tool with .cshtml file crashes Visual Studio with RC1 tools

### ISSUE THREAD

**Issue by jeffpapp** [aspnet/Tooling#293] opened 2015-11-20 23:52 UTC
If I use the merge tool in VS 2015 while trying to resolve conflicts from a Git merge it will fail on some .cshtml files.  This didn't seem to happen before installing the newer RC 1 tools this week.

I'm seeing this error message in C:\Users\<user>\AppData\Roaming\Microsoft\VisualStudio\14.0\ActivityLog.xml

```xml
  <entry>
    <record>562</record>
    <time>2015/11/20 23:37:50.833</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentNullException: Value cannot be null.&#x000D;&#x000A;Parameter name: key&#x000D;&#x000A;   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)&#x000D;&#x000A;   at Microsoft.VisualStudio.Html.Package.Extensions.ExtensionsManager.OnTextViewCreated(ITextView textView, ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.Web.Editor.Controller.TextViewConnectionListener.OnTextViewGotAggregateFocus(ITextView textView, ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Html.Package.Commands.Html.VsHtmlTextViewConnectionListener.OnTextViewGotAggregateFocus(ITextView textView, ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.Web.Editor.Controller.TextViewConnectionListener.&lt;&gt;c__DisplayClass24_0.&lt;OnTextViewConnected&gt;b__0(Object sender, EventArgs eventArgs)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent(Object sender, EventHandler eventHandlers)</description>
  </entry>
```

Here is the info from About VS in case that is helpful

```
Microsoft Visual Studio Professional 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Professional

Visual Basic 2015   00322-50050-03692-AA603
Microsoft Visual Basic 2015

Visual C# 2015   00322-50050-03692-AA603
Microsoft Visual C# 2015

Visual C++ 2015   00322-50050-03692-AA603
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (RC)   14.1.11116.0
ASP.NET and Web Tools 2015 (RC)

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.7.1   14.0.11112.0
Azure App Service Tools v2.7.1

CodeMaid   v0.8.1
CodeMaid is an open source Visual Studio extension to cleanup, dig through and simplify our C#, C++, F#, VB, PHP, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Written by Steve Cadwallader, for more information visit http://www.codemaid.net/

Common Azure Tools   1.6
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Microsoft Azure HDInsight HQL Service   2.0.2600.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2600.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601

NuGet Package Manager   3.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools

WakaTime   1.0


Web Analyzer   1.4.48
Provides static analysis directly in Visual Studio for JavaScript, TypeScript, JSX, CSS and more

Web Essentials 2015   0.5.197
Adds many useful features to Visual Studio for web developers.

```

**Comment by BillHiebert** [comment] 2015-11-21 00:14
@ToddGrun

**Comment by slaneyrw** [comment] 2015-11-24 20:03
I can confirm it's happening with me as well... same exception dump.  I'm doing a conflict resolution using source from TFS

**Comment by trichards57** [comment] 2015-11-27 22:33
I'm also having problems with the merge tool and cshtml, though I don't get a crash, I just get "Failed to start the configured compare tool."  The tool works with everything else in the project, and works on the file if I rename it to something that isn't .cshtml.  The annotate tool also doesn't work, and that crashes Visual Studio.

**Comment by trichards57** [comment] 2015-11-29 13:00
A little more information related to the HTML Editor crash:

The HTML Editor only seems to crash when there are Razor elements in code file.  For example:

    @model IEnumerable<SomeClass>
    
    <div>This is some HTML content with Razor</div>

Causes a crash while:
    
    <div>This is some HTML content without Razor</div>
    <div>Some more content</div>

Does not.

@slaneyrw Does this match your experience?

**Comment by ToddGrun** [comment] 2015-11-30 22:10
OK, I'm able to repro. Going to start taking a look into this.

**Comment by suddenelfilio** [comment] 2015-12-01 14:16
same issue here

**Comment by sayedihashimi** [comment] 2015-12-01 19:35
TFS: 168882
I've added this to our internal TFS, we will reply back here soon.

**Comment by ToddGrun** [comment] 2015-12-01 22:19
Checked in a fix for this

**Closed by ToddGrun** 2015-12-01 22:19 UTC
Labels: TFS Tracked

**Comment by suddenelfilio** [comment] 2015-12-01 22:41
How can we get this fix?

**Comment by madskristensen** [comment] 2015-12-02 17:21
This issue has been fixed and checked in. It will be in the next release of the _ASP.NET and Web Tools_ tooling update. We don't yet know if that will be RC2 or if there will be canary (weekly updates) builds released before that

**Comment by cirelli** [comment] 2015-12-02 17:51
I need it working, urgently.
How to downgrade to the last version?

**Comment by ToddGrun** [comment] 2015-12-02 18:02
Does setting Tools->Options->Text Editor->Html->Advanced->Extension Management->Identify Helpful Extensions to false work around the issue for you?

**Comment by cirelli** [comment] 2015-12-02 18:13
Worked, thanks.

**Comment by santiagohdzb** [comment] 2015-12-03 16:05
This is happening to me too, I'm using **VS2015 Enterprise with Update 1** :S


ActivityLog.xml
```
  <entry>
    <record>843</record>
    <time>2015/12/03 15:53:40.472</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentNullException: Value cannot be null.&#x000D;&#x000A;Parameter name: key&#x000D;&#x000A;   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)&#x000D;&#x000A;   at Microsoft.VisualStudio.Html.Package.Extensions.ExtensionsManager.OnTextViewCreated(ITextView textView, ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.Web.Editor.Controller.TextViewConnectionListener.OnTextViewGotAggregateFocus(ITextView textView, ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Html.Package.Commands.Html.VsHtmlTextViewConnectionListener.OnTextViewGotAggregateFocus(ITextView textView, ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.Web.Editor.Controller.TextViewConnectionListener.&lt;&gt;c__DisplayClass24_0.&lt;OnTextViewConnected&gt;b__0(Object sender, EventArgs eventArgs)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent(Object sender, EventHandler eventHandlers)</description>
  </entry>
```


Visual Studio Info
```
Microsoft Visual Studio Enterprise 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA204
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015   00322-80000-00000-AA204
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA204
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA204
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ESN   00322-80000-00000-AA204
Windows Phone SDK 8.0 - ESN

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.11120.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.7.1   14.0.11112.0
Azure App Service Tools v2.7.1

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools

TypeScript   1.7.4.0
TypeScript for Microsoft Visual Studio
```

**Comment by AlexTo** [comment] 2015-12-04 02:02
Same problem with Visual Studio 2015 Update 1 RTM. When I click "Merge Changes in Tool", VS crashes and restart.

  <entry>
    <record>826</record>
    <time>2015/12/04 01:55:59.728</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentNullException: Value cannot be null.&#x000D;&#x000A;Parameter name: key&#x000D;&#x000A;   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)&#x000D;&#x000A;   at Microsoft.VisualStudio.Html.Package.Extensions.ExtensionsManager.OnTextViewCreated(ITextView textView, ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.Web.Editor.Controller.TextViewConnectionListener.OnTextViewGotAggregateFocus(ITextView textView, ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Html.Package.Commands.Html.VsHtmlTextViewConnectionListener.OnTextViewGotAggregateFocus(ITextView textView, ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.Web.Editor.Controller.TextViewConnectionListener.&lt;&gt;c__DisplayClass24_0.&lt;OnTextViewConnected&gt;b__0(Object sender, EventArgs eventArgs)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent(Object sender, EventHandler eventHandlers)</description>
  </entry>

**Comment by aconstant** [comment] 2015-12-10 10:10
Same problem here, when comparing files with conflicts.
Please fix it asap, it is very annoying.

**Comment by QwerTech** [comment] 2015-12-10 14:19
+1

1010 ERROR System.ArgumentNullException: Value cannot be null. Parameter name: key at System.Collections.Generic.Dictionary`2.FindEntry(TKey key) at Microsoft.VisualStudio.Html.Package.Extensions.ExtensionsManager.OnTextViewCreated(ITextView textView, ITextBuffer textBuffer) at Microsoft.Web.Editor.Controller.TextViewConnectionListener.OnTextViewGotAggregateFocus(ITextView textView, ITextBuffer textBuffer) at Microsoft.VisualStudio.Html.Package.Commands.Html.VsHtmlTextViewConnectionListener.OnTextViewGotAggregateFocus(ITextView textView, ITextBuffer textBuffer) at Microsoft.Web.Editor.Controller.TextViewConnectionListener.<>c__DisplayClass24_0.<OnTextViewConnected>b__0(Object sender, EventArgs eventArgs) at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent(Object sender, EventHandler eventHandlers)   Editor or Editor Extension 2015/12/10 14:09:25.059

**Comment by EddieDL** [comment] 2015-12-16 15:50
+1

When can we expect a fix?

FYI - the workaround from @ToddGrun worked for me.

Does setting Tools->Options->Text Editor->Html->Advanced->Extension Management->Identify Helpful Extensions to false work around the issue for you?

**Comment by mike-compeat** [comment] 2015-12-17 21:39
The workaround from @ToddGrun worked for me also.

**Comment by fuzzzerd** [comment] 2015-12-18 17:02
While waiting for the updated tooling to drop; the fix @ToddGrun suggested worked for me as well.

**Comment by jonrandahl** [comment] 2016-01-01 11:57
Phew! Thanks everyone, the fix suggested by @ToddGrun worked for me too!

**Comment by Poonaka** [comment] 2016-01-08 15:20
Thanks @ToddGrun :+1:

**Comment by mittork** [comment] 2016-01-20 11:02
The workaround from @ToddGrun just works partially. I can open my .cshtml files again, but TFS compare still throws "Error occurred during difference operation: Cannot execute the configured tool.". When can we expect a fix?

**Comment by Zache** [comment] 2016-01-20 12:17
@ToddGrun is my hero!

**Comment by danuw** [comment] 2016-01-20 13:03
Workaround does not work for me either... Should that be working in combination to some other assumption pre-requisite please?
For it happens straight in the solution explorer when I try and open a .cshtml file with using statement inside...
Happened after I installed WebCompiler and uninstalling it and restarting the solution did not solve it...

**Comment by angeliquejw** [comment] 2016-01-22 16:31
Ran into this issue when attempting to merge a conflict in VS. Thankfully, @ToddGrun's workaround has saved the day.

**Comment by Willjobs94** [comment] 2016-01-26 18:55
It is also happening to me

**Comment by Willjobs94** [comment] 2016-01-26 19:03
The @ToddGrun's workaround worked for me

**Comment by erzki** [comment] 2016-01-28 13:42
@ToddGrun's workaraound did it!

**Comment by AnthonyTerra** [comment] 2016-01-28 20:07
Thank you @ToddGrun worked for me as well.

**Comment by danuw** [comment] 2016-01-28 20:21
(Only thing that worked for me then was right click/open with and select the HTML editor...)

**Comment by hyrmedia** [comment] 2016-01-29 17:26
@ToddGrun I was experiencing the same error and your proposed workaround worked for me as well. 

Visual Studio Enterprise 2015
Version 14.0.24720.00 Update 1

**Comment by bakatz** [comment] 2016-02-04 20:18
Confirmed, this is still an issue with VS2015 Update 1 and the latest ASP.NET web tools installation. Workaround worked for me and also disabled the annoying "do you want to install this helpful extension?" bar at the top as an added bonus, thanks

**Comment by rui-bruno-mendes** [comment] 2016-02-08 18:55
The workaround from @ToddGrun worked for me.

**Comment by DannyvanderKraan** [comment] 2016-02-10 13:49
This is still an issue and I have all the latest releases.

The workaround from @ToddGrun worked for me too. I am using Git with Visual Studio Online.

**Comment by deanddm** [comment] 2016-02-11 16:44
Thanks @ToddGrun. Workaround works perfectly with VS2015 Update 1. Will test again with the next VS update.

**Comment by arins** [comment] 2016-02-17 10:33
@ToddGrun  I am running VS2015 Update 1 with TFS and it worked for me. Thanks!

**Comment by Lythium** [comment] 2016-02-23 09:31
@ToddGrun Thank you, worked.

**Comment by datvm** [comment] 2016-03-03 03:49
I also have this issue. @ToddGrun workaround works.

**Comment by senatwj** [comment] 2016-03-03 15:32
Had same issue. Thanks to @ToddGrun for the fix.

Visual Studio Professional 2015
Version 14.0.24720.00 Update 1

**Comment by perlyking** [comment] 2016-03-04 09:22
@ToddGrun you legend.

**Comment by caglardursun** [comment] 2016-03-08 13:36
I've the same issue Visual Studio 14.0.2472

**Comment by evirca** [comment] 2016-03-24 07:31
This thing is happening to me when trying to merge a .cshtml page using VS2015 Enterprise. Any Fix.

**Comment by sandermvanvliet** [comment] 2016-03-24 08:03
Had the same issue appearing since yesterday, disabled the **Identify Helpful Extensions** option like @ToddGrun mentioned and that fixed it.

**Comment by showes** [comment] 2016-03-29 19:02
I experienced the same issue today merging an Html File: Clicking merge crashed VS multiple times. WorkAround by @ToddGrun fixed the issue for me.

Visual Studio Professional 2015
Version 14.0.24720.00 Update 1

**Comment by RafaelSegatto** [comment] 2016-03-29 19:36
Thx @ToddGrun worked!

**Comment by lukfcb** [comment] 2016-03-30 20:56
Thx @ToddGrun worked!

**Comment by rmosselveld** [comment] 2016-03-31 08:26
Issue still appears after installing Update 2. The fix of @ToddGrun worked for me aswell.

**Comment by niconj** [comment] 2016-04-01 20:20
Thank you @ToddGrun, you just made my friday more **awesome**!

**Comment by azaslonov** [comment] 2016-04-07 23:28
Mmm, my VS crashes the moment I get to Tools->Options->Text Editor->Html. So I @ToddGrun's suggestion doesn't work for me :(. Any other ideas?

**Comment by KJoergensen** [comment] 2016-04-08 12:42
I have tried @ToddGrun's work-around, and it worked for a while. The bug seems to be back however. This time when i try to access certain cshtml or css files...

**Comment by jcheritat** [comment] 2016-04-11 08:58
Same problem happening with VS 2015 update 2 version (info bellow),  @ToddGrun workaround working for my case.

	Microsoft Visual Studio Enterprise 2015
	Version 14.0.25123.00 Update 2
	Microsoft .NET Framework
	Version 4.6.01038

	Installed Version: Enterprise

	Architecture and Modeling Tools   00322-80000-00000-AA148
	Microsoft Architecture and Modeling Tools
		
	UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

	Visual Basic 2015   00322-80000-00000-AA148
	Microsoft Visual Basic 2015

	Visual C# 2015   00322-80000-00000-AA148
	Microsoft Visual C# 2015

	Visual C++ 2015   00322-80000-00000-AA148
	Microsoft Visual C++ 2015

	Visual F# 2015   00322-80000-00000-AA148
	Microsoft Visual F# 2015

	Windows Phone SDK 8.0 - ENU   00322-80000-00000-AA148
	Windows Phone SDK 8.0 - ENU

	Application Insights Tools for Visual Studio Package   5.2.60328.3
	Application Insights Tools for Visual Studio

	ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.11120.0
	ASP.NET and Web Tools 2015 (RC1 Update 1)

	ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
	For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

	ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
	For additional information, visit http://www.asp.net/

	Azure App Service Tools v2.8.2   14.0.20115.0
	Azure App Service Tools v2.8.2

	Chutzpah Context Menu   4.2.1
	Enables you to run JavaScript unit tests via Chutzpah from the context menu

	Common Azure Tools   1.7
	Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

	DataFactoryProject   1.0
	Microsoft Data Factory Package

	Entity Framework Power Tools   1.0
	Adds useful design-time DbContext features to the Visual Studio Solution Explorer context menu. 

	When right-clicking on a file containing a derived DbContext class, the following context menu functions are supported:

	1) View Entity Data Model - Displays the underlying Code First model in the Entity Framework designer.
	2) View Entity Data Model XML - Displays the EDMX XML representing the underlying Code First model.
	3) Generate Views - Generates pre-compiled views used by the EF runtime to improve start-up performance. Adds the generated views file to the containing project.

	GhostDoc   4.9.15086.0
	GhostDoc automatically generates XML documentation comments.

	GitHub.VisualStudio   1.0
	A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

	ILSpy.AddIn   1.0
	Integration of the ILSpy Decompiler into Visual Studio.

	JavaScript Language Service   2.0
	JavaScript Language Service

	JavaScript Project System   2.0
	JavaScript Project System

	KofePackagePackage Extension   1.0
	KofePackagePackage Visual Studio Extension Detailed Info

	Microsoft Azure Data Factory Node Node   1.0
	Azure Data Factory extension for Visual Studio Server Explorer.

	Microsoft Azure HDInsight HQL Service   2.0.2900.0
	Language service for Hive query

	Microsoft Azure HDInsight Tools for Visual Studio   2.0.2900.0
	An integrated development environment for HDInsight application development.

	Microsoft Azure Mobile Services Tools   1.4
	Microsoft Azure Mobile Services Tools

	Microsoft Azure Tools   2.7
	Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601

	Microsoft Azure Tools   2.8
	Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.40114.1

	Microsoft MI-Based Debugger   1.0
	Provides support for connecting Visual Studio to MI compatible debuggers

	NuGet Package Manager   3.4.0
	NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

	Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
	Microsoft Office Developer Tools for Visual Studio 2015 ENU

	PreEmptive Analytics Visualizer   1.2
	Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

	Python Tools for Visual Studio   2.2.40315.00
	Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

	Python Tools for Visual Studio - Django Integration   2.2.40315.00
	Provides templates and integration for the Django web framework.

	Python Tools for Visual Studio - Profiling Support   2.2.40315.00
	Profiling support for Python projects.

	Sassy Studio   0.2.0.0
	Provides some support for sass / scss in visual studio

	SQL Server Data Tools   14.0.60311.1
	Microsoft SQL Server Data Tools

	T4 Toolbox   14.0.0.0
	Extends code generation capabilities of Text Templates.

	TypeScript   1.8.29.0
	TypeScript tools for Visual Studio

	Visual C++ for Cross Platform Mobile Development (Android)   14.0.25116.00
	Visual C++ for Cross Platform Mobile Development (Android)

	Visual C++ for Cross Platform Mobile Development (iOS)   14.0.25116.00
	Visual C++ for Cross Platform Mobile Development (iOS)

	Visual Studio Tools for Apache Cordova   Update 8
	Visual Studio Tools for Apache Cordova

	Visual Studio Tools for Universal Windows Apps   14.0.25123.00
	The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

	WakaTime   1.0


	Web Compiler   1.10.306
	Compiler for LESS, Sass and CoffeeScript files

	Web Essentials 2015.1   1.0.211
	Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015

	Workflow Manager Tools 1.0   1.0
	This package contains the necessary Visual Studio integration components for Workflow Manager.

	XAML Spy   2.7.0
	XAML Spy for Visual Studio
	Copyright © First Floor Software. All rights reserved.

	Spy all the XAML!
	http://xamlspy.com

**Comment by vmandic** [comment] 2016-04-12 09:26
Thanks @ToddGrun, saved me on VS2015 Update 1!

**Comment by aju31a** [comment] 2016-04-12 10:52
This problem was even in VS2015 Update 2
but  @ToddGrun's worked like a charm for me
Thanks Todd

**Comment by brentdavid2008** [comment] 2016-04-14 13:19
+1 for in VS 2015 Update 2, disabling the extensions tool, worked at least for this particular merge.  

Please notify whoever owns the extension or just remove it all together.  I've asked it to stop notifying me with the 'dont ask again' and that never works either.

Thanks for the workaround @ToddGrun.  

have a good one.

**Comment by viewtance** [comment] 2016-04-19 11:23
VS2015 version 14.0.25123.00 Update 2 also with this issue, but the method from @ToddGrun not working for me, is any other approach to fix?

**Comment by adam-dorin** [comment] 2016-04-20 07:31
@ToddGrun :+1:  thx man ! your workaround worked for me also/

**Comment by sfmskywalker** [comment] 2016-04-26 19:55
@ToddGrun Dude you saved my evening. Cheers!

**Comment by RClendenon** [comment] 2016-04-27 16:08
I am using Visual Studio 2015 Update 2 with Microsoft ASP.NET and Web Tools version 14.1.20203.0 on Windows 10 and this is still an issue. The workaround provided by @ToddGrun works for me.

**Comment by oising** [comment] 2016-04-29 12:16
Running update 2 on vs2015, same crash, but thankfully the workaround works. I'm merging a regular .html file, not even a cshtml.

```
System.ArgumentNullException: Value cannot be null. Parameter name: key at System.Collections.Generic.Dictionary`2.FindEntry(TKey key) at Microsoft.VisualStudio.Html.Package.Extensions.ExtensionsManager.OnTextViewCreated(ITextView textView, ITextBuffer textBuffer) at Microsoft.Web.Editor.Controller.TextViewConnectionListener.OnTextViewGotAggregateFocus(ITextView textView, ITextBuffer textBuffer) at Microsoft.VisualStudio.Html.Package.Commands.Html.VsHtmlTextViewConnectionListener.OnTextViewGotAggregateFocus(ITextView textView, ITextBuffer textBuffer) at Microsoft.Web.Editor.Controller.TextViewConnectionListener.<>c__DisplayClass24_0.<OnTextViewConnected>b__0(Object sender, EventArgs eventArgs) at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent(Object sender, EventHandler eventHandlers)
```

**Comment by vcsjones** [comment] 2016-05-02 18:49
Echoing what @oising said - same exception, same work around works. Running a Fully up-to-date VS2015 with Update 2.

**Comment by oising** [comment] 2016-05-02 21:49
@vcsjones @madskristensen Agreed. I don't know why this is closed. It's not fixed in update 2.

**Comment by tomexou** [comment] 2016-05-06 08:59
Change the value from true to false as below:
![image](https://cloud.githubusercontent.com/assets/12069870/15068698/b9f86dd4-13ab-11e6-867e-e5e304662a3a.png)

VS2015 update 2 will not be crashed on opening *.chtml files.

**Comment by oising** [comment] 2016-05-10 15:08
If they can't fix this issue after two point releases, I suggest they take the easier route and update the text from "Identify Helpful Extensions" to "Crash when opening HTML files", and default it to `False.`

**Comment by tsfinley** [comment] 2016-05-11 13:34
@tomexou Your solution worked for me. Thank you for posting it.

**Comment by alanmcbee-fsl** [comment] 2016-05-12 21:15
@tomexou @ToddGrun The workaround solved a problem trying to resolve a markdown (.md) merge conflict in VS2015 update 2. Looking forward to a permanent fix...

**Comment by baxterworks** [comment] 2016-05-17 06:00
Ping - any chance of reopening this?

**Comment by madskristensen** [comment] 2016-05-17 06:23
The fix for this issue was released in the new ASP.NET Core RC2 tooling

**Comment by gordonglas** [comment] 2016-05-17 15:51
Just ran into this issue and installing ASP.NET Core RC2 tooling for visual studio 2015 fixed it for me. I'm no longer getting an error that crashes visual studio when opening the merge tool. Thanks @madskristensen

**Comment by MarcusPozzan** [comment] 2016-05-18 19:27
ping any update on correction?

**Comment by madskristensen** [comment] 2016-05-18 19:31
@MarcusPozzan It's fixed in the [.NET Core Tooling Preview 1 for Visual Studio 2015](https://www.microsoft.com/net/download#tools)

**Comment by flaviodamaiajr** [comment] 2016-05-23 14:02
Thanks @ToddGrun ! It worked!

**Comment by falconmick** [comment] 2016-07-22 00:42
how is this still a problem...

**Comment by improwise** [comment] 2016-08-19 19:27
This just confirm my impression that VS2015 is probably the biggest piece of crap software I've ever used. VS 2015 is by far the worst version so far and each update only seem to make it even worse. And I've been using it since 1997 so I have lots of Visual Studio versions to compare it with. We are seriously considering giving up on .NET all together as there as just so many problems these days :(

**Comment by brentdavid2008** [comment] 2016-08-20 15:38
@improwise I'm not sure it's that bad.  These guys do an amazing job with a product that has been through so many different iterations.  It's practically impossible to have something completely bug free. Users will be users. We use .net all the time and don't have 'so many problems these days'  However, you are always more than welcome to create your own product, plus, there's always notepad++. 
that NEVER crashes. 

Happy Coding

**Comment by improwise** [comment] 2016-08-20 16:42
@brentdavid2008  Main problem is that it seems to get worse with every attempt to fix something. The Update packages seem to cause as many problems as they fix. Merge crashing, save buttons not working, even copy & paste not working sometimes.  Even my colleagues that has always praised Visual Studio as the best IDE (I used to be one of them) have now kind of given up on VS2015 and many has gone back to Visual Studio 2013 just to get some real work done and not just trying to figure out workaround to IDE problems constantly. I really hope MS gets their act together here...

And I completely agree on Notepad++, had VS2015 been anything close to that, I would be very very happy :)

**Comment by residentx10** [comment] 2016-08-20 16:47
Get the community edition not the RC...jeez. RC is a release candidate.
Your wrong for even posting this issue :-)

**Comment by improwise** [comment] 2016-08-20 17:19
Not sure who you are referring to, if it is me I run Visual Studio Update 3 Patch 1 but was lead hear as I was googling to try to to solve one of the many problems with VS2015.

**Comment by C4Technologies** [comment] 2016-09-25 07:33
This suggestion from @ToddGrun  worked for me:

Tools->Options->Text Editor->Html->Advanced->Extension Management->Identify Helpful Extensions to false is a work around the issue.

**Comment by voyager18** [comment] 2016-10-25 09:03
The issue is still present in Visual Studio 2015 Update 3. The solution offered by @ToddGrun is already valid and it has worked for me.

**Comment by lrazak** [comment] 2016-11-16 09:48
I still got this bug in Visual Studio 2015 Professional Update 3. I installed .NET Core 1.0.1 - VS 2015 Tooling Preview 2 and this fixed the issue for now.
