### ISSUE TITLE
Preview2: Unable to debug project aftert "buildOptions" > "outputName" changed

### ISSUE THREAD

**Issue by antonGritsenko** [aspnet/Tooling#620] opened 2016-06-28 09:23 UTC
I've set "buildOptions" > "outputName" to value != name of the folder where project stored and clear the bin folder. Re-build.
Now I'm getting error when try to debug project in Visual Studio 2015:
_Unable to start process <Path_To_Old_Name.exe>. Process creation failed with error: The system cannot find the file specified._

Any workarounds?

**Comment by barrytang** [comment] 2016-06-29 01:10
TFS Bug#235749

**Comment by dynamiclynk** [comment] 2016-08-06 01:35
Same issue here on v1, if I set the outputName property in project.json to the name of the folder that contains ./bin it will start debugging if any other name it fails but the exe is there.

So say folder is C:\code\my_app\bin\ 
and outputName: "myApp"  --> .\bin\myApp.exe

debug will fail statis it can't find the process

But if outputName: "my_app"  --> .\bin\my_app.exe

then debug starts...is this by design?

**Comment by mlorbetske** [comment] 2016-09-13 16:41
This will be fixed with the move to csproj for .NET Core projects. Unfortunately with xproj/project.json projects, for the VS scenarios, the folder name must match the output name.

**Closed by mlorbetske** 2016-09-13 16:41 UTC
Labels: TFS Tracked
