### ISSUE TITLE
Visual Studio 2015 Community with ASP.NET Beta 8 restarts when opening index.cshtml file

### ISSUE THREAD

**Issue by gokalpi** [aspnet/Tooling#260] opened 2015-11-03 10:27 UTC
After I installed ASP.NET and Web Tools 2015 (Beta8) to my system, Visual Studio 2015 has started crashing and restarting itself when I open cshtml files.

My configuration is as follows;

Microsoft Visual Studio Community 2015   14.0.23107.0 D14REL
Microsoft .NET Framework   4.6.00081
Visual Basic 2015
Visual C# 2015
Visual C++ 2015
Application Insights Tools for Visual Studio Package   1.0
ASP.NET and Web Tools 2015 (Beta8)   14.0.61012.0
ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
CodeMaid   v0.8.1
Common Azure Tools   1.5
GenerateUnitTest   1.0
Microsoft Azure Mobile Services Tools   1.4
NuGet Package Manager   3.2.0
Open Command Line   2.0.159
PreEmptive Analytics Visualizer   1.2
SQL Server Data Tools   14.0.50730.0
Web Essentials 2015   0.5.193

**Comment by BillHiebert** [comment] 2015-11-03 20:47
@ToddGrun

**Comment by ToddGrun** [comment] 2015-11-03 20:57
Does this happen consistently? Does this still occur after flushing your MEF cache (extensions and updates -> Online -> Clear MEF Component Cache. After restarting VS, Tools->Clear MEF Component Cache...) 

If you are still able to reproduce at that point, I would love to help investigate why this is occurring. Please let me know what you find. Thanks!

-- Todd

**Comment by sayedihashimi** [comment] 2015-11-03 22:08
For the Tools Option that Todd states I think you need the extension https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd

**Comment by gokalpi** [comment] 2015-11-04 06:59
I installed this addon, cleared cache and restarted Visual Studio. But nothing is happening, when I double clicked on cshtml files. I think default editor for cshtml files (HTML Editor) is not triggering or not working properly. I can open these files with Source Code Text Editor.

**Comment by emreolgun** [comment] 2015-11-04 07:17
@ToddGrun,

I have the exact same problem (Visual Studio 2015 Community with ASP.NET Beta 8). It happens consistently. I have flushed MEF cache. 

Whenever I use a capital "i" letter in the cshtml file (like Index.cshtml, TestI.cshtml), it crashes when I try to add a new file or edit an existing file.

My system language is Turkish, and Visual Studio language is English.

Thanks.

--
Emre

**Comment by emreolgun** [comment] 2015-11-04 07:36
Hi, I cleaned and build my solution. The problem is solved!

--
Emre

**Comment by gokalpi** [comment] 2015-11-04 08:31
I think capital I letter is my problem too. But cleaning cache, build, rebuild doesn't matter.

**Comment by ToddGrun** [comment] 2015-11-04 17:42
I've verified the problem exists when using the capital dotted I in the name and that the problem is in code, not in the MEF cache. For now, you can work around the problem by not using the capital dotted I in your razor page names, and I'll work on getting a fix in for this as soon as possible. Thanks a ton for reporting this and providing such a good description of the problem!

**Comment by ToddGrun** [comment] 2015-11-05 00:41
OK, I've checked in a fix which should make it into the next ASP.Net 5 tooling release. Thanks again!

**Closed by ToddGrun** 2015-11-05 00:41 UTC
