### ISSUE TITLE
Scaffolding controllers using EntityFramework not working at all

### ISSUE THREAD

**Issue by Cnordbo** [aspnet/Tooling#411] opened 2016-02-21 12:39 UTC
On blank projects, if i try to create a new Controller with actions using EntityFramework - it allways returns the error message: 

> There was an error running the selected code generator: 
> There was an error getting the type "failtest.Models.TestModelClass". 
> Try rebuilding the project.

I created a detailed post about it here, with step-by-step on how to reproduce, as well as allready tried solutions. 
http://stackoverflow.com/questions/35187813/web-api-scaffolding-error-running-the-selected-code-generator

Running the latest version of VS2015 Professional (v. 14.0.24720.00 Update 1) and Azure SDK. This issue also happened before Update 1.

**Comment by sayedihashimi** [comment] 2016-03-18 02:36
@Cnordbo scaffolding has some requirements today. We have an item on the backlog to support adding dependencies to projects which are missing them, but for the past few weeks we've been busy porting from dnx -> dotnet so we have not been able to get to that yet. We are still working on dnx -> dotnet.

This issue was previously reported at https://github.com/aspnet/Tooling/issues/290, and there are some details about the dependencies to add at https://github.com/aspnet/Tooling/issues/290#issuecomment-158465907. This is an item that I'm tracking and hoping to get to soon, but I am not sure when we will be able to start that work. I'm going to close this now since it's a duplicate of #290.

Thanks for the report.

**Closed by sayedihashimi** 2016-03-18 02:36 UTC
