### ISSUE TITLE
Linking Core RC2 "Portable" with full .NET 4.61 within MSVS

### ISSUE THREAD

**Issue by piotrpMSFT** [aspnet/Tooling#560] opened 2016-06-07 01:34 UTC
## Steps to reproduce

Wrap and Link a .NET 4.61 project into a .NET Core RC2 portable executable (MvcMovie) using MSVS 2015 Enterprise Update 2.

It was working with the wrapped assembly compiled/wrapped as .NET 46 and Core Framework target "net46".
## Expected  behavior

No build errors.  
## Actual behavior

Build Error:

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : Object reference not set to an instance of an object.

Double clicking the error navigates to this line, something must not be set:

 <Dnx
      RuntimeExe="$(SDKToolingExe)"
      Condition="'$(_DesignTimeHostBuild)' != 'true'"
      ProjectFolder="$(MSBuildProjectDirectory)"
      Arguments="$(_BuildArguments)"
      />
## Environment data

[xproj_json.zip](https://github.com/dotnet/cli/files/292475/xproj_json.zip)

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

Any workaround (env variable) would be appreciated.  Apologies if this is not the correct place to post this type of issue.

moving from https://github.com/dotnet/cli/issues/3310 on behalf of @crokusek

**Comment by crokusek** [comment] 2016-06-07 01:40
The cause of this error may be related to some of the dependent assemblies being version 4.6  instead of 4.6.1.  Once I changed them all to 4.6.1 the error stopped appearing.

Hopefully the error message could be improved at least.

**Comment by sayedihashimi** [comment] 2016-06-14 18:38
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231147&fullScreen=false&_a=edit">231147</a>

**Comment by mkaltner** [comment] 2016-07-22 00:59
We've seen a similar issue and disabling NuGet auto restore seems to fix it.

1. Disable NuGet restore (Tools -> NuGet Package Manager -> Package Manager Settings, uncheck Allow NuGet to download missing packages)
2. Delete *.lock.json
3. Run “dotnet restore” from cmd line in solution folder
4. Build/run project.

Some have had luck with re-enabling NuGet restore afterwards, others haven't.

**Comment by sayedihashimi** [comment] 2017-01-09 18:07
Sorry for the delay here. We've had a lot of updates over the past few months and I believe that this is working now in VS2017 RC. Can you try with the latest VS2017 and try again? I'll close this now, but please reopen if this issue still persists.

**Closed by sayedihashimi** 2017-01-09 18:07 UTC
Labels: TFS Tracked
