### ISSUE TITLE
xUnit async tests shows up as “External” in VS2015

### ISSUE THREAD

**Issue by hennys** [aspnet/Tooling#130] opened 2015-08-04 20:41 UTC
I have a problem that all my async xUnit tests are showing up as External in the Test Explorer in VS2015 when grouped by project. They will still run when calling Run All in the test explorer, but as they are considered External almost all of the VS2015 integration does not work, e.g. the navigation (click in test explorer to get to test) is not working, the Run/Debug Tests in the context menu never triggers the test, test status icons doesn't show and Code Lens won't find these tests. Changing the test to run in-sync fixes all these problems.

1. Create a project with a single class with a simple async method:
2. Create a test project with a test class containing a async and a sync test method
3. Build and open the Test Explorer window, grouped by project

Expected: Both test shows up under the Project.

Actual: Sync test shows up under Project, async under External.

Code example:
```c#
public class TestedClass
{
    public async Task<bool> TestedMethod()
    {
        return await Task.FromResult(true);
    }
}

public class TestedClassTest
{
    [Fact]
    public async Task AsyncTest()
    {
        var subject = new TestedClass();
        var result = await subject.TestedMethod();
        Assert.True(result);
    }

    [Fact]
    public void SyncTest()
    {
        var subject = new TestedClass();
        var result = subject.TestedMethod().Result;
        Assert.True(result);
     }
}
```

I'm running the RTM version of VS2015 Professional with SDK version 1.0.0-beta6 with the only dependency being the xunit.runnet.aspnet 2.0.0-aspnet-beta6 package. The same bug existed with beta5 as well, have not checked any earlier. Main project targets dnx451 and dnxcore50, test project dnx451, but triaging different frameworks show now change to this behavior.

Question also asked at http://stackoverflow.com/questions/31799380/xunit-async-tests-shows-up-as-external-in-vs2015.

**Comment by victorhurdugaci** [comment] 2015-08-04 20:47
@vijayrkn

**Comment by vijayrkn** [comment] 2015-08-04 22:10
The reason VS tooling shows all async xUnit tests as External is because source information is not getting passed to VS from the TestHost. @rynowak - Is there a bug tracking this?

**Comment by rynowak** [comment] 2015-08-05 15:52
Dupe of aspnet/Testing#86

**Comment by sayedihashimi** [comment] 2015-09-30 16:55
@rynowak since this is being tracked at https://github.com/aspnet/Testing/issues/86 can we close this?

**Comment by rynowak** [comment] 2015-09-30 17:33
This was fixed already. Suggest closing

**Comment by sayedihashimi** [comment] 2015-10-06 17:44
Closing based on @rynowak comments

**Closed by sayedihashimi** 2015-10-06 17:44 UTC
