### ISSUE TITLE
Deploy to Azure and Docker missing from the "Publish" window

### ISSUE THREAD

**Issue by Flavien** [aspnet/Tooling#158] opened 2015-08-23 20:36 UTC
I am using ASP.NET 5 Beta 6. When trying to publish, I only get one option: Publish to file system.

![image](https://cloud.githubusercontent.com/assets/296540/9430056/a305fe80-49de-11e5-882a-f5f37c41d458.png)

I am expecting to see at least "Deploy to Azure Websites", and "Deploy to Docker VM", since I have installed the Docker tools for VS. I do have the "Deploy to Azure Websites" for non ASP.NET 5 web applications.

Any idea why this is missing?

**Comment by sayedihashimi** [comment] 2015-08-23 22:08
Do you have a webroot property defined in project.json? VS seems to think this is a class library project.

**Comment by Flavien** [comment] 2015-08-23 22:10
No, I removed `webroot` because the project is a ASP.NET Web API project which doesn't have a webroot. Do I need to add one for the deploy to work?

**Comment by sayedihashimi** [comment] 2015-08-23 22:25
Yeah do that for now.

@billhie I think we may need a better way to identify a web project.

**Comment by Flavien** [comment] 2015-08-23 22:32
Thanks, I got the Azure publish showing up now. The Docker deploy is still missing though.

**Comment by Flavien** [comment] 2015-08-23 22:41
Just found out that if I set the webroot to `.` instead of empty, I don't have to have a "dummy folder".

**Comment by sayedihashimi** [comment] 2015-08-23 22:44
Do you have the docket tools installed https://visualstudiogallery.msdn.microsoft.com/0f5b2caa-ea00-41c8-b8a2-058c7da0b3e4 ?

**Comment by sayedihashimi** [comment] 2015-08-23 22:46
Yes setting to . is fine.

**Comment by Flavien** [comment] 2015-08-23 23:26
> Do you have the docket tools installed 

Yes I have those installed.

**Comment by davidfowl** [comment] 2015-08-23 23:38
Why does the we root matter for docker publish?

**Comment by sayedihashimi** [comment] 2015-08-24 00:32
webroot is for MSDeploy publish, not sure why docker isn't working.

**Comment by sayedihashimi** [comment] 2015-08-25 17:55
@yanchenw any idea why docker publish is not enabled here?

**Comment by yanchenw** [comment] 2015-08-25 19:07
Docker tools use the same way Web Tools identifies web project, it only shows for ASP.NET 5 web and console app. @Flavien if you create a new ASP.NET 5 web application, will Docker option show up?

**Comment by Flavien** [comment] 2015-08-25 19:41
> if you create a new ASP.NET 5 web application, will Docker option show up? 

That's a good question. For some reason, I don't have a project template for ASP.NET 5 websites. I do have the beta 6 tools installed. Maybe this is related?

**Comment by sayedihashimi** [comment] 2015-08-25 19:59
@Flavien
>That's a good question. For some reason, I don't have a project template for ASP.NET 5 websites. I do have the beta 6 tools installed. Maybe this is related?

What do you mean there are no ASP.NET 5 templates? Are you using Visual Studio 2015? If so when you do File->New Project->Web->ASP.NET Web Application you should see ASP.NET 5 Preview templates. If you don't then check the value for .NET Framework on the New Project Dialog and make sure it's set to .net 4.5.1+.

**Comment by Flavien** [comment] 2015-08-25 23:11
This is what I have:

![image](https://cloud.githubusercontent.com/assets/296540/9481937/c2bf623a-4b86-11e5-9e6e-f49b3cf32358.png)

I'm assuming "ASP.NET Web Application" is ASP.NET 4.6.

**Comment by sayedihashimi** [comment] 2015-08-25 23:13
Can you show the dialing after you pick ASP.NET Web Application?

**Comment by Flavien** [comment] 2015-08-25 23:15
You're right, it does show a second screen with both the ASP.NET 4.6 and 5.0 templates.

Publish is still missing Docker on a new project though (It has "Azure Web Apps", "Import" and "File System").

**Comment by Flavien** [comment] 2015-08-25 23:16
And this shows Docker tools should be installed:

![image](https://cloud.githubusercontent.com/assets/296540/9482034/a5877634-4b87-11e5-88a8-4d4e5cb30787.png)

**Comment by yanchenw** [comment] 2015-08-25 23:24
@Flavien It seems you installed the wrong version or the new version is not installed correctly, the new version should be 0.6.
Can you go to https://visualstudiogallery.msdn.microsoft.com/0f5b2caa-ea00-41c8-b8a2-058c7da0b3e4, re-download the installer, uninstall the old Docker tools and retry?

**Comment by sayedihashimi** [comment] 2015-09-30 16:49
@Flavien did the [reply from yanchenw](https://github.com/aspnet/Tooling/issues/158#issuecomment-134769175) solve this for you?

**Comment by Flavien** [comment] 2015-09-30 17:40
@sayedihashimi Yes it did, thanks.

**Comment by sayedihashimi** [comment] 2015-10-06 17:35
@Flavien OK closing this now

**Comment by hemangmaradiya** [comment] 2016-05-24 09:19
Hi,
I have downloaded latest Docker tools for VS from  https://visualstudiogallery.msdn.microsoft.com/0f5b2caa-ea00-41c8-b8a2-058c7da0b3e4 
and installed it.
I have also installed DotNetCore.1.0.0.RC2-VS2015Tools.Preview1 before installing Docker Tools.

Now when I create a ASP.NET Core web application. In project Publish option I am also not able to see Docker option in Profile.

I have also installed Docker client tools. As well as I have uninstalled and then install Docker Tools for visual studio. 
Could you please help me to resolve this.
![image](https://cloud.githubusercontent.com/assets/19549086/15498788/9c97e442-21be-11e6-9329-a81b5b0c054b.png)


Thanks
Hemang

**Comment by maestrocoder** [comment] 2016-06-16 22:59
Please reopen.  The issue has returned.  Using all the latest on version 0.20 and 0.21.  We are missing the option to publish to docker VM

**Comment by Jboice** [comment] 2016-06-17 22:20
I am also having this issue with version 0.21.

**Comment by azlamsalam** [comment] 2016-07-15 20:57
Having issue with 0.30 as well

**Comment by sayedihashimi** [comment] 2016-07-15 21:31
Reopened based on comments

**Comment by mlorbetske** [comment] 2016-07-18 18:38
TFS Bug#241359

**Comment by NCarlsonMSFT** [comment] 2016-07-18 19:42
This was a feature of the Docker Tools for Visual Studio 2015 extension (http://aka.ms/dockertoolsforvs) that was removed in 0.14 in favor of the new developer inner loop experience. For more information about our new experience see: https://azure.microsoft.com/en-us/documentation/articles/vs-azure-tools-docker-edit-and-refresh/

**Comment by mlorbetske** [comment] 2016-07-19 15:58
Since @NCarlsonMSFT indicates that this is by design (and that the Docker tools have an alternate gesture) can this be closed?

**Comment by mlorbetske** [comment] 2017-07-19 06:55
Closing this based on the above comments

**Closed by mlorbetske** 2017-07-19 06:55 UTC
Labels: Issue Tracker Notification Posted, TFS Tracked

**Comment by wayne-o** [comment] 2018-06-29 10:34
I am getting this now when trying to push a non web project to docker hub. all of my API projects get the option to publish to docker but not the console app ones - I can't even tell which property or feature is distinguishing them as they are all console apps - just some are running  kestrel?!

**Comment by wayne-o** [comment] 2018-06-29 10:37
It is this: `<Project Sdk="Microsoft.NET.Sdk.Web"> ` - if the project has this then it can be published to docker - if it has this `<Project Sdk="Microsoft.NET.Sdk">`  then it can't

Is this by design?
