### ISSUE TITLE
Unable to Add New Scaffolded Item... 

### ISSUE THREAD

**Issue by RossAndrewMcLeod** [aspnet/Tooling#382] opened 2016-01-24 02:31 UTC
I have been playing around with EF-7 for a couple of months now. Approx 2-3 weeks ago I noticed that the context menu item for Add => New Scaffolded Item.. has disappeared. I have been at a loss to explain or source the problem after doing multiple source comparisons I found the following: 

1. Projects on my desktop were suffering the problem
2. Opening a project on my laptop (without internet connected) do not show the problem
3. Comparison of project.json files appears that they are the same
4. I made a comment on issue: Add new scaffolded item missing #290 but thus far no answer (BTW I think this is a different problem to the original).
5. I opened a copy of your project UniconStore on both my laptop & desktop and took screen shots (please find attached). Note that the context menu still there on the project unable to update itself (I'm assuming some NuGet package thing/issue).

Any assistance would be appreciated

Ross

![add new scaffolded item](https://cloud.githubusercontent.com/assets/16367947/12534104/1e958538-c29e-11e5-9687-5a89d0cdfb33.PNG)
![no add scaffolded item](https://cloud.githubusercontent.com/assets/16367947/12534105/1e9bcc72-c29e-11e5-9bb2-089e6f7cd277.PNG)

**Comment by seganaUK** [comment] 2016-01-29 11:16
@RossAndrewMcLeod Did you ever find a solution for this?

Just installed VS Community 2015 + ASP.NET 5 RC1 and I do not see this option. I've made sure I have the required dependencies that every other post references, but no joy at all.

**Comment by RossAndrewMcLeod** [comment] 2016-01-30 00:08
@seganaUK  No joy yet still waiting for someone to respond. I'm wondering if I've placed this post in the wrong place. As far as I can tell (from other posts) there is on caveat and that is to have Authentication: set to => Individual User Accounts. I did however manage to generate scaffolding via the command line but the generated scripts were in an older style and I couldn't get them to work. Good luck, I found when they worked that this was a good way to get started.

**Comment by sayedihashimi** [comment] 2016-02-01 20:23
Sorry for the delay here. We had another issue with a similar title that I was getting confused by see https://github.com/aspnet/Tooling/issues/290.

@RossAndrewMcLeod could you share your project with me? I'd like to see if I get the menu option for the same project.

**Comment by RossAndrewMcLeod** [comment] 2016-02-01 21:20
That's easy it's @rowanmiller UnicornStore project straight out of the box (from GitHub). But just in case I'll copy mine here as well.
[UnicornStore.zip](https://github.com/aspnet/Tooling/files/113007/UnicornStore.zip)

I did make a comment on #290 but I think that this is a different issue. The originator of that issue didn't use Authentication: set to => Individual User Accounts...

Hope you can find this. Just one other thing. Have I posted this in the correct place? Perhaps it should have been posted on [EntityFramework]???

**Comment by sayedihashimi** [comment] 2016-02-01 23:04
@RossAndrewMcLeod thanks.

So it's showing up for me, see image below.

![addsc](https://cloud.githubusercontent.com/assets/1283154/12734373/e5e7cd2e-c8f4-11e5-9ecd-32348d234358.png)

A few questions.
 - What OS are you using?
 - Can you take a screenshot in VS of Help->About and paste it here?
 - Are you having any issues building/running the project?

**Comment by RossAndrewMcLeod** [comment] 2016-02-02 05:36
My OS is as follows:
![myos](https://cloud.githubusercontent.com/assets/16367947/12740718/fbc89314-c9c9-11e5-8f67-a09304d2aed6.PNG)

CS => About:
![image](https://cloud.githubusercontent.com/assets/16367947/12740764/8067ccb6-c9ca-11e5-8134-96515dc23f65.png)

Copy of the info from about box:
Microsoft Visual Studio Community 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA129
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA129
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA129
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-20000-00000-AA129
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.11120.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.1   14.0.11123.0
Azure App Service Tools v2.8.1

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.31121.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

MySQL for Visual Studio   1.2.5
Data design and management tools for MySQL.  Copyright © 2007-2015 Oracle, Inc.

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools

TypeScript   1.7.6.0
TypeScript for Microsoft Visual Studio

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual Studio Tools for Universal Windows Apps   14.0.24720.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Xamarin   4.0.0.1717 (1390b70)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.0.0.35 (d300845)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   9.3.99.33 (ea30b32)
Visual Studio extension to enable development for Xamarin.iOS.

This is really strange @sayedihashimi perhalps it's because my computer is up side down compared to yours. :)

**Comment by sayedihashimi** [comment] 2016-02-03 18:24
I'm still trying to reproduce this and still unsuccessful. One combo that I have not yet tried (because I'm having a hard time finding the installers) is having ASP.NET 5 RC1 + Azure SDK 2.8.1. If you are running into this and you have Azure SDK 2.8.1, try upgrading to the latest Azure SDK (2.8.2 at this time) and let me know if that fixes it.

**Comment by RossAndrewMcLeod** [comment] 2016-02-03 22:33
Ok will let you know how that goes. I tried the repair on VS2015 but that didn't work. That was 3-4 hours of my life I won't get back. I'm away from desk at the moment but will try ASAP.

**Comment by sayedihashimi** [comment] 2016-02-03 23:33
@RossAndrewMcLeod I'm sorry you're running into this. I've been trying my best to reproduce this but I'm still unble to.

**Comment by RossAndrewMcLeod** [comment] 2016-02-04 04:37
@sayedihashimi it's not your fault and I do understand that you are doing your best. You may have misunderstood my sense of humor as a complaint. I would love to get back to this (ASP.NET stuff) as soon as possible. The strange thing about this is it did work and I was happily getting into the web programming. Then for some reason it stopped. I have some projects (on my laptop) that show the context menu, but if I build them it will go away.

Here is the latest:

1. As mentioned above I have run a repair of VS2015
2. I have upgraded to Azure SDK 2.8.2
3. I have run a repair on ASP.NET 5 RC1 (soon to be known as Core 1.0)

All to no avail... Back to you and thanks, Ross

**Comment by sayedihashimi** [comment] 2016-02-04 19:16
@RossAndrewMcLeod if you have a machine where you do not see the command can you share me the results of Help->About in VS? I'm still trying to reproduce this so that we can fix the underlying issue. I have a felling a lot of people are impacted.

**Comment by RossAndrewMcLeod** [comment] 2016-02-04 20:23
The machine that I do not see the command:
![image](https://cloud.githubusercontent.com/assets/16367947/12828479/33bc5b14-cbd9-11e5-89fb-8a6001ec14f2.png)

And the details:

Microsoft Visual Studio Community 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA129
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA129
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA129
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-20000-00000-AA129
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.11120.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.2   14.0.20115.0
Azure App Service Tools v2.8.2

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DataFactoryProject   1.0
Microsoft Data Factory Package

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft Azure Data Factory Node Node   1.0
Azure Data Factory extension for Visual Studio Server Explorer.

Microsoft Azure HDInsight HQL Service   2.0.2900.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2900.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.40114.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

MySQL for Visual Studio   1.2.5
Data design and management tools for MySQL.  Copyright © 2007-2015 Oracle, Inc.

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools

TypeScript   1.7.6.0
TypeScript for Microsoft Visual Studio

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual Studio Tools for Universal Windows Apps   14.0.24720.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Web Essentials 2015   1.0.204
Adds many useful features to Visual Studio for web developers.

Xamarin   4.0.0.1717 (1390b70)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.0.0.35 (d300845)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   9.3.99.33 (ea30b32)
Visual Studio extension to enable development for Xamarin.iOS.

**Comment by RossAndrewMcLeod** [comment] 2016-02-04 20:35
I have a machine where I do see the command
![laptopvs2015about](https://cloud.githubusercontent.com/assets/16367947/12828529/7b56fd94-cbd9-11e5-8f84-eaa340e8a489.PNG)

Microsoft Visual Studio Community 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA715
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA715
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA715
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-20000-00000-AA715
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.11120.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.1   14.0.11123.0
Azure App Service Tools v2.8.1

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DataFactoryProject   1.0
Microsoft Data Factory Package

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft Azure Data Factory Node Node   1.0
Azure Data Factory extension for Visual Studio Server Explorer.

Microsoft Azure HDInsight HQL Service   2.0.2900.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2900.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.31121.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Compact & SQLite Toolbox   4.4.0
SQL Server Compact & SQLite Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools

TypeScript   1.7.4.0
TypeScript for Microsoft Visual Studio

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual Commander   2.3
For more information about Visual Commander, see the website at https://vlasovstudio.com/visual-commander/.
Copyright (c) 2013-2015 Vlasov Studio.

Visual Studio Tools for Universal Windows Apps   14.0.24720.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

There are a couple slight differences:

No Command => Microsoft .NET Framework Version **4.6.01038**
With Command => Microsoft .NET Framework Version **4.6.01055**

No Command => Azure App Service Tools v2.8.2 14.0.20115.0 (updated yesterday)
With Command => Azure App Service Tools v2.8.1   14.0.11123.0
**I think we can rule this one out...**

**No Command has some extra packages**:
Web Essentials 2015 1.0.204
Adds many useful features to Visual Studio for web developers.

Xamarin 4.0.0.1717 (1390b70)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android 6.0.0.35 (d300845)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS 9.3.99.33 (ea30b32)
Visual Studio extension to enable development for Xamarin.iOS.

**Comment by RossAndrewMcLeod** [comment] 2016-02-11 03:06
Hi @sayedihashimi  I have just applied the latest ASP.NET RC1 Update 1 and the problem has cured itself. Thanks for all your help. I will close this issue now if you like.

**Comment by sayedihashimi** [comment] 2016-02-19 17:32
@RossAndrewMcLeod ok great to hear. I've still been unable to repro this so maybe we fixed it already :) I think you were the only remaining person who is still running into this so I'll close this now.

**Closed by sayedihashimi** 2016-02-19 17:32 UTC

**Comment by ArcadeKIlla** [comment] 2018-06-19 16:06
Hey! I know this has been dead for a while but I am having the same issues cross-platform. My Macbook and Windows 10 computer both lack the controller and new scaffolding options.
