### ISSUE TITLE
Keep seeing "Based on your project, we have identified extensions..."

### ISSUE THREAD

**Issue by Eilon** [aspnet/Tooling#305] opened 2015-11-25 02:34 UTC
I always click "Don't Show Again" and it shows up every time I re-open VS in a CSHTML file.

Can this just go through the regular VS notifications system instead?

**Comment by sayedihashimi** [comment] 2015-11-25 02:39
Is that web essentials?

**Comment by Eilon** [comment] 2015-11-25 07:20
No I think it's @madskristensen 's thing he showed at MVP Summit.

**Comment by ToddGrun** [comment] 2015-11-25 16:36
@alexgav has some context with this

**Comment by sayedihashimi** [comment] 2015-11-25 16:37
TFS: 167862

**Comment by JeremyCade** [comment] 2015-12-04 04:31
I can confirm:

1) That I have the same issue on both ASP.NET 4.6 & ASP.NET 5 solutions. 
2) Have this issue in the latest VS 2015 14.0.24720.00 Update 1

![screen shot 2015-12-04 at 2 27 18 pm](https://cloud.githubusercontent.com/assets/492782/11581895/597c0952-9a93-11e5-82f1-fb3fc4c51f92.png)

![screen shot 2015-12-04 at 2 29 57 pm](https://cloud.githubusercontent.com/assets/492782/11581915/98ac8142-9a93-11e5-819e-0bb8b996d20e.png)

**Comment by Eilon** [comment] 2015-12-04 18:41
I've seen other people on the ASP.NET team also hitting this.

**Comment by alexgav** [comment] 2015-12-04 19:53
I reproed the issue and checked in a fix for it. It will be available in RC2 (currently in WTE Main). 

The issue is that a setting is not getting persisted. The workaround is to manually change the setting. Go to Tools->Options->Text Editors->HTML->Advanced and make sure Identify Helpful Extensions is set to false. (Note, it will be "false" already if you dismissed the yellow bar in the current VS session. In this case just the action of showing the options dialog and closing it with "OK" will be enough to persist the setting).

**Closed** 2015-12-04 20:02 UTC
Labels: TFS Tracked

**Comment by Eilon** [comment] 2015-12-05 02:56
Can this just go through the regular VS Notifications system? I'd like to avoid having popups, popunders, poparounds, etc.
