### ISSUE TITLE
Can't Execute Web Application after pressing F5

### ISSUE THREAD

**Issue by gauravsha** [aspnet/Tooling#403] opened 2016-02-10 18:54 UTC
Hi,

My web app (MVC6) was working fine when I switched off my machine yesterday. Today I press F5, build pass and then web app runs for a moment and switches off back.

**Below is what output window shows:**

'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'Microsoft.Dnx.Host.Clr'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\ashu_\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\Microsoft.Dnx.Host.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\ashu_\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\Microsoft.Extensions.PlatformAbstractions.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\ashu_\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\Microsoft.Dnx.Loader.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\ashu_\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\Microsoft.Dnx.ApplicationHost.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\ashu_\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\Microsoft.Dnx.Runtime.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\ashu_\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\Microsoft.Dnx.Compilation.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\ashu_\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\Microsoft.Dnx.Compilation.Abstractions.dll'. Cannot find or open the PDB file.
The program '[11268] dnx.exe' has exited with code 1 (0x1).
The program '[1032] iisexpress.exe' has exited with code -1 (0xffffffff).

**This is my Project.json**

{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Bower": "1.3.11",
    "EntityFramework.Core": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final"
  },

  "commands": {
    "ef": "EntityFramework.Commands",
    "web": "Microsoft.AspNet.Server.Kestrel"
  },

  "frameworks": {
    "dnx461": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ]
}

**Global.Json
**
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-rc1-final"
  }
}

Please help.

**Comment by sayedihashimi** [comment] 2016-02-19 17:09
@gauravsha can you share a sample project/solution which we can use to reproduce this?

**Comment by ltheONEl** [comment] 2016-03-12 18:59
I am getting this too.  Can run in debug one time there after I get this error.  I have to re-boot the PC before I can run again.  Publishing the project to IIS always runs with no problem.  Seems to be related to visual studio and IISExpress.

**Comment by sayedihashimi** [comment] 2016-04-08 21:40
I"m unable to reproduce this problem. Is this still happening for you? If so does it also happen for new projects created with File->New Project or just existing projects/solutions?

**Comment by ltheONEl** [comment] 2016-04-10 23:50
I have one project that will not run in debug ay all. dnx exits immediately with -1

**Comment by sayedihashimi** [comment] 2016-05-27 20:38
This issue is pretty old. We recently released RC2 https://blogs.msdn.microsoft.com/webdev/2016/05/16/announcing-asp-net-core-rc2/. I'm hoping that this is no longer an issue so I'm closing this. If this is still an issue with RC2 please reopen this.

**Closed by sayedihashimi** 2016-05-27 20:38 UTC
