### ISSUE TITLE
Discussion for pre-release build 'Nightly - 6/7/16'

### ISSUE THREAD

**Issue by balachir** [aspnet/Tooling#577] opened 2016-06-09 17:22 UTC
This is a discussion thread for pre-release build 'Nightly - 6/7/16'.

**Comment by zigzag95** [comment] 2016-06-09 18:51
Please a little summary of changes and Breaking changes

**Comment by balachir** [comment] 2016-06-09 19:38
For tooling, this build contains mostly bug fixes on top of the tooling support you had for the .NET Core 1.0.0 RC2 release. One significant change (as called out in the [Release Notes and Known Issues section](https://github.com/aspnet/Tooling#release-notes-and-known-issues)) is the default for web application template is now 'No authentication' instead of 'Individual Accounts'. 

There shouldn't be any breaking changes with respect to tooling, it should be mostly backwards-compatible. If you have a project targeting .NET Core 1.0.0 RC2, you will be able to continue developing with that project after installing the new tooling.

**Comment by fenneh** [comment] 2016-06-09 20:19
Possibly a bit pedantic, but why is this under aspnet org and not the dotnet org?

**Comment by Eilon** [comment] 2016-06-10 04:35
@fenneh just historical reasons, nothing more. And perhaps the fact that @balachir sits in the same team room as many ASP.NET team members 😄

**Comment by zigzag95** [comment] 2016-06-10 06:18
During last community standup it was confirmed that asp and dotnet team are merged.

**Comment by vnbaaij** [comment] 2016-06-10 08:44
Will there also be an installer for Visual Studio "15" preview 2?

**Comment by fenneh** [comment] 2016-06-10 09:47
@Eilon - Only reason I mention it is the switching from ASP.Net Core to .Net Core all over the place is a little confusing, even in the README. Something to keep in mind!

**Comment by Eilon** [comment] 2016-06-10 16:21
@vnbaaij there will be eventually, yes.

@fenneh yeah it's a work in progress to get everything merged and lined up. Your feedback is well-taken 😄

**Comment by tmds** [comment] 2016-06-11 06:05
Is there a way to get the version of dotnet and sdk included in this prerelease for the linux distros? Does this version of the cli understand netstandard1.6 (cfr https://github.com/dotnet/cli/issues/3488).?

**Comment by ArieJones** [comment] 2016-06-11 12:26
It seems that the installer is hanging on Microsoft Visual Studio Preparation. I see no disk activity at all.. no CPU usage.. I can provide the log file if necessary

**Comment by lucamorelli** [comment] 2016-06-11 20:51
I don't know if this is the right place to report this, anyway.
1. I created as asp.net core .net fx app, and a classic class library (not .net core), and tried ad add a reference to the library inside the web app project. I can add the reference, but the build fails. I remember time ago was a supported feature, but I don't know if the current status. If is not possible anymore, I think is better prevent it, at least using the add reference wizard, it's a it confusing.
2. could be possible to execute npm task or gulp tasks directly from solutions explorer? selecting package.json, gulpfile, in the context menu could be added a voice containing the list of the available commands, letting the direct execution of them.

**Comment by lucamorelli** [comment] 2016-06-11 21:02
I created a core web app using dot net dx selecting framework 4.5.2. deleting the .lock.json file and restoring I obtaing this message

```
Errors in c:\users\luca\documents\visual studio 2015\Projects\WebApplication1\src\WebApplication1\WebApplication1.xproj
    Package Microsoft.DotNet.ProjectModel.Loader 1.0.0-preview2-002913 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.ProjectModel.Loader 1.0.0-preview2-002913 supports: netstandard1.6 (.NETStandard,Version=v1.6)
    Package Microsoft.DotNet.Cli.Utils 1.0.0-preview2-002913 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.Cli.Utils 1.0.0-preview2-002913 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netstandard1.6 (.NETStandard,Version=v1.6)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
    Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-002913 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-002913 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netstandard1.6 (.NETStandard,Version=v1.6)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
```
Is this normal?

**Comment by balachir** [comment] 2016-06-13 22:36
@tmds, thanks for the feedback. I have updated the [Release Notes section](https://github.com/aspnet/Tooling#release-notes-and-known-issues) for this pre-release build and called out the dotnet version info included in this build.

@ArieJones, did your install ever complete? If you are still blocked, please open a new issue in this repo and we can investigate further.

@lucamorelli, regarding (1), reference from asp.net core (.NET Framework) app to classic class library seems to be working fine for me with this pre-release build as well as with RC2 tooling build. Are you seeing these issues with the 'Nightly 6/7/16' pre-release build or with RC2 tooling? Can you open one or more separate issues for the items you called out? I think that would help us look into those and investigate into each one as needed.

**Comment by ArieJones** [comment] 2016-06-14 11:40
@balachir No my install never completed. I will possibly try again later today and then submit an issue if I can still not get it to go.

**Comment by tmds** [comment] 2016-06-14 11:51
debugging no longer works for me: Unable to attach to CoreCLR. A debug component is not installed. https://github.com/aspnet/Tooling/issues/584

**Comment by sayedihashimi** [comment] 2016-06-14 18:37
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231137&fullScreen=false&_a=edit">231137</a>

**Comment by lucamorelli** [comment] 2016-06-14 21:27
@balachir looks like it's working. there are two confusing things switching framework versions: 
1. after I change version of the library I need often a complete rebuild of the solution, otherwise the web app continues to use the older version of the library. 
2. changing the fx version of the library remove the link inside the project.json of the asp.net core web app.

**Comment by benaadams** [comment] 2016-06-15 09:45
Can't install the tooling as it complains Update 3 RC is not completely installed

![image](https://cloud.githubusercontent.com/assets/1142958/16075245/08d3a30c-32e6-11e6-8ec3-fef32de3f444.png)

Log file: https://gist.github.com/benaadams/8ba16afb6dd1180f1306efc195186a5f

**Comment by joeloff** [comment] 2016-06-15 15:02
We have seen a few machines where VSU doesn't always install fully, so we added a new check for two registry keys to ensure the values match.

For now, to work around this and bypass the check, you can run the EXE from a command prompt and then pass SKIP_VSU_CHECK=1 at the end.

The registry keys we look at are below. Can you confirm their presence/values?

1. HKLM\Software\Wow6432Node\Microsoft\Updates\Microsoft Visual Studio 2015\vsupdate_KB3022398 (PackageVersion value) – I’ve seen a few isolated cases where this key could be missing as well.
2.       And then depending on the SKU, we look at the UpdateVersion value under one of these
-          HKLM\Software\Wow6432Node\Microsoft\DevDiv\vs\Servicing\14.0\professional
-          HKLM\Software\Wow6432Node\Microsoft\DevDiv\vs\Servicing\14.0\community
-          HKLM\Software\Wow6432Node\Microsoft\DevDiv\vs\Servicing\14.0\enterprise[Oren Novotny]

**Comment by benaadams** [comment] 2016-06-15 16:40
Nope, none of those keys

![image](https://cloud.githubusercontent.com/assets/1142958/16088544/8b33350e-331f-11e6-80bd-beb650671f1c.png)

![image](https://cloud.githubusercontent.com/assets/1142958/16088565/a383c4fc-331f-11e6-98ef-c40005e590eb.png)

I reformatted and clean installed from MSDN just prior to RC2 tooling

Visual Studio Enterprise 2015 with Update 2 (x86 and x64) - DVD (English)
en_visual_studio_enterprise_2015_with_update_2_x86_x64_dvd_8510142.iso

So maybe that didn't install the upgrade keys?

**Comment by lahma** [comment] 2016-06-15 17:36
Had the same problem, ".\DotNetCore.1.0.0.RC3-27-VS2015Tools.Preview2.exe SKIP_VSU_CHECK=1" did the trick.

**Comment by joeloff** [comment] 2016-06-15 17:49
@benaadams Do you have a 64-bit or 32-bit OS? The keys I sent were for a 64-bit OS. If you're on 32-bit, then the VS keys would be under HKML\SOFTWARE\Microsoft\DEVDIV (without the Wow6432Node part).

@lahma, glad to hear it worked

**Comment by benaadams** [comment] 2016-06-15 17:53
64-bit: Windows 10 Pro x64 Insider Preview, Build 14366.rs1_release.160610-1700

Unless the periodic Windows preview updates clear the keys

**Comment by joeloff** [comment] 2016-06-15 18:01
@benaadams We've been suspicious that Windows updates might clear the keys under SOFTWARE\Microsoft\Updates, but haven't found any hard evidence, just a few isolated cases where folks have been reporting that the keys don't exist on their machine.

The VS keys under DEVDIV should remain untouched as all the individual SKU components register their version information there. 

The screenshot you sent showed DEVDIV\servicing\14.0 whereas the VS keys are HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\DevDiv\vs\Servicing\14.0

**Comment by benaadams** [comment] 2016-06-15 18:10
Ah, Update Version: 14.0.25402 - though also have community and professional nodes

![image](https://cloud.githubusercontent.com/assets/1142958/16091652/84bef5ca-332c-11e6-8b18-d088b0aefe0b.png)

![image](https://cloud.githubusercontent.com/assets/1142958/16091684/af51ea36-332c-11e6-9dd0-f48cfb95662b.png)

Re upgrades, I do generally have to reinstall the Service Fabric SDK after on of the full Windows Preview version updates

**Comment by joeloff** [comment] 2016-06-15 18:31
ok, that's expected. The CPE SKUs follow a Russian doll model, so they'll start with community and then potentially add Professional or Enterprise on top depending on the actual SKU you have.

**Comment by benaadams** [comment] 2016-06-15 19:14
I get the updated server GC section from File->New with this installed :+1:

**Comment by benaadams** [comment] 2016-06-16 01:45
Hmm... issue with MVC being ` netstandard1.6` now from File->New 

Do I need to install or delete something to get `.NETCoreApp,Version=v1.0` to be compatible with `netstandard1.6 (.NETStandard,Version=v1.6)`?

```ini
error: Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-002913 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-002913 supports:
error:   - net451 (.NETFramework,Version=v4.5.1)
error:   - netstandard1.6 (.NETStandard,Version=v1.6)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.
error: Package Microsoft.AspNetCore.Mvc 1.0.0-rc3-21167 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.AspNetCore.Mvc 1.0.0-rc3-21167 supports:
error:   - net451 (.NETFramework,Version=v4.5.1)
error:   - netstandard1.6 (.NETStandard,Version=v1.6)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.
```

```json
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc3-004338",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc3-21167",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc3-21167",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc3-21167",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc3-21167",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0-rc3-21167",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc3-21167",
    "Microsoft.Extensions.Logging": "1.0.0-rc3-21167",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc3-21167",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc3-21167"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview2-21167",
      "imports": "portable-net45+win8+dnxcore50"
    }
  },

```

**Comment by benaadams** [comment] 2016-06-16 02:07
`dotnet --version` say is using preview1; will update paths

**Comment by benaadams** [comment] 2016-06-16 02:16
This was caused by:
![image](https://cloud.githubusercontent.com/assets/1142958/16103438/a04921e6-3370-11e6-8a01-b1755c18a97f.png)

`C:\Program Files (x86)\dotnet` being earlier in my path than 
`C:\Program Files\dotnet`

However only `C:\Program Files\dotnet` was updated to preview2

**Closed** 2017-01-06 21:15 UTC
Labels: discussion, TFS Tracked
