### ISSUE TITLE
Vs2015 inside Html editor, editing a knockout binding crashes due to chakrals.dll

### ISSUE THREAD

**Issue by valeriob** [aspnet/Tooling#112] opened 2015-07-22 05:55 UTC
Hi, i'm having this repeatable crashes in vs2015 while inside the html editor of a razor view (mvc 5).
The message box with "Visual studio 2015 has stopped working pops out", on the bottom left corner it says "The Javascript Language service is processing your request in the background..." and windows error reporting says Fault Module Name = chakrals.dll.

**Comment by sayedihashimi** [comment] 2015-07-30 03:14
+ @barrytang @mayurid @madskristensen FYI crash reported

**Comment by sayedihashimi** [comment] 2015-07-31 16:20
@valeriob I have created an internal TFS bug to track this. We will get back to you.

TFSID 1206646

**Comment by albernhagen** [comment] 2015-08-06 18:54
I am also getting this error while editing JS files in a Cordova project.  Here's additional windows event log information:

Faulting application name: devenv.exe, version: 14.0.23107.0, time stamp: 0x559b7ead
Faulting module name: chakrals.dll, version: 11.0.10131.0, time stamp: 0x5567e542
Exception code: 0xc0000005
Fault offset: 0x0019cc8e
Faulting process id: 0xf74
Faulting application start time: 0x01d0d076f6c0b2b6
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Faulting module path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\WebClient\Language Service\chakrals.dll
Report Id: 075937e4-3c6b-11e5-9eae-ecf4bb394b4d

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 2C63CC8E
Stack:
   at Microsoft.VisualStudio.JSLS.Engine.IAuthorFileAuthoring.GetCompletions(Int32, Microsoft.VisualStudio.JSLS.Engine.AuthorCompletionFlags)
   at Microsoft.VisualStudio.JSLS.Engine.Proxy.AuthorFileAuthoringProxy+<>c__DisplayClass10_0.<GetCompletions>b__0()
   at GuardMethodClass.GuardMethod(System.Func`1<System.Object>, System.Func`2<System.Exception,Boolean>, System.Func`2<System.Exception,System.Object>)
   at Microsoft.VisualStudio.JSLS.Shared.ExceptionFilter.Guard(System.Func`1<System.Object>, System.Func`2<System.Exception,Boolean>, System.Func`2<System.Exception,System.Object>)
   at Microsoft.VisualStudio.JSLS.Engine.ServiceCore+GuardRecord.Guard()
   at Microsoft.VisualStudio.JSLS.Engine.ServiceCore.Guard[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`1<System.__Canon>, System.Func`1<System.__Canon>)
   at Microsoft.VisualStudio.JSLS.Engine.Proxy.Proxy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GuardAndProxy[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`1<System.__Canon>, System.Func`1<System.__Canon>, System.Func`2<System.__Canon,System.__Canon>)
   at Microsoft.VisualStudio.JSLS.Engine.Proxy.AuthorFileAuthoringProxy.GetCompletions(Int32, Microsoft.VisualStudio.JSLS.Engine.AuthorCompletionFlags)
   at Microsoft.VisualStudio.JSLS.DynamicScriptLoading.ScriptLoaderReferenceUpdateTask.Run()
   at Microsoft.VisualStudio.JSLS.Engine.SingleThreadTask.<Execute>b__24_0()
   at GuardMethodClass.GuardMethod(System.Func`1<System.Object>, System.Func`2<System.Exception,Boolean>, System.Func`2<System.Exception,System.Object>)
   at Microsoft.VisualStudio.JSLS.Shared.ExceptionFilter.Guard(System.Func`1<System.Object>, System.Func`2<System.Exception,Boolean>, System.Func`2<System.Exception,System.Object>)
   at Microsoft.VisualStudio.JSLS.Engine.SingleThreadTask.Execute()
   at Microsoft.VisualStudio.JSLS.Engine.SingleThreadScheduler.WorkerThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by darrenshrwd** [comment] 2015-08-11 02:39
VS2015 is very slow for me, keep getting delays with "the javascript language service is processing your request in the background" and it has crashed for me 4 times this morning.

**Comment by steve-warren** [comment] 2015-08-11 21:25
I am also experiencing this issue when editing KO bindings within an MVC razor page. Specifically, edits to data-bind="" attribute causes VS 2015 to crash under chakrals.dll.

**Comment by ahmad-farid** [comment] 2015-08-12 20:04
@valeriob @albernhagen  @darrenshrwd @steve-warren 
Would you be able to provide the JS file/project where you're seeing VS crash and what you were doing by then (typing, opening the file... etc.) Thanks!

**Comment by valeriob** [comment] 2015-08-13 10:21
I can only in 2 weeks from now. But any crash in chakrals should not bring vs with him.


----- Messaggio originale -----
Da: "ahmad-farid" <notifications@github.com>
Inviato: ‎12/‎08/‎2015 16:04
A: "aspnet/Tooling" <Tooling@noreply.github.com>
Cc: "Valeriob" <valeriob@gmail.com>
Oggetto: Re: [Tooling] Vs2015 inside Html editor, editing a knockout bindingcrashes due to chakrals.dll (#112)

@valeriob @albernhagen @darrenshrwd @steve-warren 
Would you be able to provide the JS file/project where you're seeing VS crash and what you were doing by then (typing, opening the file... etc.) Thanks!

**Comment by scriptdude** [comment] 2015-08-14 19:02
I'm also experiencing this whenever I start editing any Javascript file.

This is from my crash report:

```Version=1
EventType=APPCRASH
EventTime=130840406139754939
ReportType=2
Consent=1
UploadTime=130840406141702282
ReportIdentifier=37d170f8-429b-11e5-832f-485ab619a01e
IntegratorReportIdentifier=18371a17-cb09-434f-afbb-ec4cdba7a0b2
WOW64=1
NsAppName=devenv.exe
Response.BucketId=54957bf4cd22e7670273744586a89ef0
Response.BucketTable=1
Response.LegacyBucketId=107472457379
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=devenv.exe
Sig[1].Name=Application Version
Sig[1].Value=14.0.23107.0
Sig[2].Name=Application Timestamp
Sig[2].Value=559b7ead
Sig[3].Name=Fault Module Name
Sig[3].Value=chakrals.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=11.0.10131.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=5567e542
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=00397075
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.10240.2.0.0.256.27
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1043
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=0760
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=07603a43fc8f06601a3b753de6944e96
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=f627
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=f627e476ea80de9ec0d6024228d06334
UI[2]=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
UI[3]=Microsoft Visual Studio 2015 has stopped working
UI[4]=Windows can check online for a solution to the problem and try to restart the program.
UI[5]=Check online for a solution and restart the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program

**Comment by usefulBee** [comment] 2015-08-21 16:40
As 'scriptdude' mentioned this ""The Javascript Language service is processing your request in the background..."" behavior happens when editing any js file in VS2015. It is very annoying! I never experienced such message or delay in VS2013.

**Comment by rogihee** [comment] 2015-08-25 13:20
I am encountering the same problem with editing angular JS controller files. Extremely annoying! It freezes the complete IDE.

**Comment by darrenshrwd** [comment] 2015-08-25 22:05
My issue was with an angular file, a number of modules within a few IIFE.

**Comment by bodinaren** [comment] 2015-08-31 09:41
I got the same crashes too, on average 3-5 times per hour. I got a Cordova project. It's crashing even when I'm not actively using VS but only got it opened in the background.

```
Faulting application name: devenv.exe, version: 14.0.23107.0, time stamp: 0x559b7ead
Faulting module name: chakrals.dll, version: 11.0.10131.0, time stamp: 0x5567e542
Exception code: 0xc0000005
Fault offset: 0x00397075
Faulting process id: 0x1758
Faulting application start time: 0x01d0e3cc4acedb4e
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Faulting module path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\WebClient\Language Service\chakrals.dll
Report Id: b18d06ed-74fb-4f83-830a-58cf5e2f7fcb
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by 12michel34** [comment] 2015-08-31 14:07
Same issue here while editing an angular.js file. After opening the file vs2015 crashes after 1-2 min.

**Comment by BillHiebert** [comment] 2015-09-01 16:55
The team responsible for that assembly is aware of the issue and working on a fix - most likely VS Update 1.

**Comment by peterski74** [comment] 2015-09-14 03:09
Remove unnecessary js file references from scripts/_references.js this fixed it for me. I actually removed all references and don't even get that message at all. Good luck!

**Comment by tdorlus** [comment] 2015-09-14 04:09
I am also experiencing the same issue. VS crashes sporadically when I modify/open JS Files in the cordova application.

**Comment by yechongbo** [comment] 2015-09-19 17:45
I am developing cordova apps and facing this issue either. It keeps freezing and crashing until i removed all JS references indicated by this path HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\JavaScriptLanguageService, everything seems to work faster and no more processing in background.

**Comment by plwade** [comment] 2015-09-27 11:29
I'm also getting this problem with VS2015 RTM crashing re. 'The Javascript Language service is processing your request in the background'.

@yechongbo What do you mean by 'removed all JS references'. Do you mean remove all files with a JS extension? Does this include all sub folders?
Any help appreciated.

BTW: I've raised a bug with Microsoft, but I'm not holding my breath for a quick response.

**Comment by jamez14** [comment] 2015-10-01 14:01
I get extreme lagging (not being able to type or do anything inside VS 2015 for anywhere from 10 seconds to 35 seconds). No crashes, but I receive the same message `The Javascript Language service is processing your request in the background` during the slowdown. 

The JS files can be anything from 200 lines to 15, such as:
```
(function () {
    'use strict';

    angular.module('acAdmin')
            .filter('percentage', percentageFilter);

    percentageFilter.$inject = ['$filter'];

    function percentageFilter($filter) {
        return function (input) {
            return $filter('number')(Math.abs(input) * 100) + '%';
        };
    }

})();
```

**Comment by alexgav** [comment] 2015-10-07 02:23
Hi jamez14,

Several people mentioned they were able to fix the issue by removing unneeded (or all) references from _references.js file. Would you please see if this fixes the issue for you as well? Find the _references.js file in your project, remove all content, save, see if that fixes the problem. I would love to hear back.

Thanks,
Alex

**Comment by jamez14** [comment] 2015-10-07 02:29
Alex,

I've been using VS like that for the past few days, and yes, that fix made everything perform as expected. I removed all entries from _references.js. Sorry, I probably should've followed up after a day of usage.

Thanks!
James

**Comment by alexgav** [comment] 2015-10-07 02:37
James, 

Thank you for letting me know! It looks like a performance issue in VS (though some folks are reporting crashes, which is even worse). Could you tell me how many entries you had in your project?

Also, if you (or anybody else on the thread) have a project you could share that reproduces the issue, that would be great. It should be fine to have a large number of entries in _references.js. It provides (or at least supposed to) better IntelliSense at design time (not used at runtime). Deleting entries from it is a workaround, but not a good fix and should not be necessary.

Thanks,
Alex

**Comment by jamez14** [comment] 2015-10-07 12:29
Hi Alex,

I had 46 references at the time of me writing that. But I remember it happening with 10 (which is likely about where the project began). I don't have a project at the moment that I can share unfortunately, but I'll see if I can dig up an open source example that reproduces the issue. 

Thanks again!

**Comment by vernjensen** [comment] 2015-10-22 02:37
I'm having this same issue, but in Visual Studio 2013 Update 5. I hope that whatever fix is developed for 2015 gets released for 2013 as well.

**Comment by EdMaurer** [comment] 2015-10-22 19:57
Hi all, I work on the team that builds the JavaScript and TypeScript editing experience in Visual Studio. Through crash telemetry, we've diagnosed and fixed the issues that caused 70% of the crash hits in VS 2015 chakrals.dll. I'm optimistic that the robustness of JavaScript editing will improve significantly with the next VS 2015 update. 

@vernjensen, sorry to say that the fixes do not target VS 2013. 

Regards,
Ed

**Comment by thatgirlcancode** [comment] 2015-10-23 12:48
I've moved on to a better IDE. I highly recommend using VS Code for editing all of your front-end files. It's in preview, but I haven't had any problems with it... https://code.visualstudio.com/

**Comment by Utsavv** [comment] 2015-10-23 15:23
I am also facing same issue while working on cordova project. Its becoming almost impossible to work due to frequent crashes!

Faulting application name: devenv.exe, version: 14.0.23107.0, time stamp: 0x559b7ead
Faulting module name: chakrals.dll, version: 11.0.10131.0, time stamp: 0x5567e542
Exception code: 0xc0000005
Fault offset: 0x0019cc8e
Faulting process id: 0x340c
Faulting application start time: 0x01d10da5e5bd040a
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Faulting module path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\WebClient\Language Service\chakrals.dll
Report Id: 3da5b416-7999-11e5-973a-2016d896ffc1

**Comment by vernjensen** [comment] 2015-10-23 20:50
@EdMaurer -- thanks for the note. I can just upgrade to VS 2015 and target 2013's API when building C++ code.

**Comment by vernjensen** [comment] 2015-10-23 20:54
@EdMaurer -- what update will fix 70% of the chakrals.dll crashes? 2015.1? or 2015.2? I see that a 2015.1 preview is available here:

https://www.microsoft.com/en-us/download/details.aspx?id=49189

Just wondering if that contains the fixes or if I should wait.

**Comment by EdMaurer** [comment] 2015-11-02 21:37
@vernjensen Sorry, lost track of this thread. You probably want this version:

[https://www.visualstudio.com/en-us/news/vs2015-update1-vs.aspx](https://www.visualstudio.com/en-us/news/vs2015-update1-vs.aspx)

**Comment by briwg** [comment] 2015-11-23 10:17
I've installed the VS2015 Update 1 RC on a Win 7 machine with 16GB RAM but am still having the same problems. When debugging Cordova in VS2015 / Ripple the devenv.exe *32 process grows rapidly after pressing ctrl+S to refresh, increasing by about 400mb each time. This seems to happen even when very little is happening in the view. 

After a few refreshes devenv.exe *32 grows to >2.5GB and Visual Studio freezes and restarts. It makes working very difficult and I've found it easier to edit the .js files in the Google Chrome dev tools. 

Any suggestions? 

PS: I've tried on a Win 10 installation and experienced the same behaviour.

**Comment by EdMaurer** [comment] 2015-11-23 17:05
@briwg In your installation, what is the file version of this file? C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\WebClient\Language Service\chakrals.dll

**Comment by briwg** [comment] 2015-11-23 17:26
@EdMaurer, the file version is: 

11.0.10240.16531

The memory usage grows rapidly when hitting a breakpoint in a .js file after pressing ctrl+S. Sorry, I didn't make clear in my previous post that if there isn't a breakpoint set in the .js file saving to refresh Ripple doesn't seem to be causing a problem.

**Comment by EdMaurer** [comment] 2015-11-23 18:14
@briwg, hmm, that's the latest version. Any indication from the Windows event log about what binary the final out-of-memory exception is attributed to? I'm trying to understand if your problem is in chakrals.dll or some other component.

**Comment by briwg** [comment] 2015-11-23 18:29
@EdMaurer: The last entry in the Event Viewer is below. There are many similar entries appearing before this one.

Fault bucket , type 0
Event Name: Dev11NonFatalError
Response: Not available
Cab Id: 0

Problem signature:
P1: ScriptedSandbox64.exe
P2: 14.0.24627.0 D14REL
P3: 562f11b6
P4: Title:Dom Version:1.0 Domain:http://microsoft.com/
P5: 14.0.24627.0
P6: 562f11b6
P7: file:///C:/Program8412ef4d-920f-11e5-a230-005056c00008Files8412ef4d-920f-11e5-a230-005056c00008(x86)/Microsoft8412ef4d-920f-11e5-a230-005056c00008Visual8412ef4d-920f-11e5-a230-005056c00008Studio%2014.0/Common7/IDE/PrivateAssemblies/plugin.vs.js
P8: 7681
P9: Unable to get property 'source' of undefined or null reference
P10: ScriptedPluginHost

**Comment by EdMaurer** [comment] 2015-11-23 18:52
@briwg, I'm not sure what to say about that event. It may be related to your problem, but what I would like to find are the events occurring in devenv.exe. My event log query skills are limited. A simple filter that I created didn't return what I wanted, so I can't tell you how to find them.

**Comment by briwg** [comment] 2015-11-23 19:01
@EdMaurer, these entries relating to devenv.exe appear, not sure if they help?

Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: devenv.exe
P2: 14.0.24627.0
P3: 562f17e9
P4: StackHash_d84d
P5: 0.0.0.0
P6: 00000000
P7: c000041d
P8: 74b24f5d
P9: 
P10: 



Faulting application name: devenv.exe, version: 14.0.24627.0, time stamp: 0x562f17e9
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc000041d
Fault offset: 0x74b24f5d
Faulting process id: 0x1b14
Faulting application start time: 0x01d12606ba30ecbd
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Faulting module path: unknown
Report Id: 494e1a9a-9210-11e5-a230-005056c00008

**Comment by briwg** [comment] 2015-11-28 13:48
@EdMaurer: I've had chance to investigate further. The problem only occurs when I'm pointing to a local install of the Ionic framework. For example, if the 1.1.1 release (or earlier versions) is included as a folder in www root and referenced in index.html like this:

<script src="1.1.1/js/ionic.bundle.min.js"></script>
devenv.exe rapidly grows when hitting a breakpoint causing VS2015 to run out of memory and restart.

Alternatively, If I point at the an ionic bundle on a http address like below there is no problem and I can hit breakpoints without devenv going crazy:: 

<script src="http://code.ionicframework.com/1.1.1/js/ionic.bundle.min.js"></script>

Any ideas what is going on?

**Comment by binaryfog** [comment] 2015-11-29 15:22
I uninstalled TypeScript for Visual Studio 2015 and the VS 2015 seems to work fine now . 
My project is an ionic framework one with google maps in it.

**Comment by EdMaurer** [comment] 2015-11-30 18:44
@briwg Based on the Windows event log, any clue what DLL in the devenv.exe process the out-of-memory is attributed to?

**Comment by EdMaurer** [comment] 2015-12-11 17:16
Are people still seeing this problem after installing the [RTM version of Dev14 Update 1](http://blogs.msdn.com/b/visualstudio/archive/2015/11/30/visual-studio-update-1-rtm.aspx)?

**Comment by PauloMarques89** [comment] 2015-12-11 18:52
not, after upgrading everything is working normally.

**Comment by binaryfog** [comment] 2015-12-15 20:52
Upgrade fixed the issue .

**Comment by jasonbrandt42** [comment] 2016-01-13 18:44
Yes!  The issue still occurs after applying update 1 

Javascript language service crashes VS2015

**Comment by Zache** [comment] 2016-01-21 10:28
I'm still getting this error

**Comment by Deracination** [comment] 2016-02-09 00:38
I encountered frequent lagging with 'javascript language service in background' in 14.0.24720.00 update 1 until I set '_references.js' autosync enabled=false, and culled out about 30 ionic and angular-related files from the references, leaving around 20 app-specific ones.

**Comment by jasonbrandt42** [comment] 2016-02-09 17:18
Ok, cool.   I will give that a try and see what happens.  Should only take
a few hours here to see if the lagging begins again.

**Comment by jasonbrandt42** [comment] 2016-02-12 16:50
Yes, this worked!

Thanks!

**Comment by Zache** [comment] 2016-02-16 07:47
But there is still another underlying problem, because my project doesn't
have a _referencesjs

2016-02-12 17:50 GMT+01:00 renley <notifications@github.com>:

> Yes, this worked!
>
> Thanks!
>
>
>
> On Tue, Feb 9, 2016 at 10:18 AM, Renley Renfield <mrrmrenfield@gmail.com>
> wrote:
>
>
> > Ok, cool. I will give that a try and see what happens. Should only take
> > a few hours here to see if the lagging begins again.
> >

**Comment by LaoR-UA** [comment] 2016-05-16 14:07
I also have no _references.js in th project folder. I have just opened a simple file without loading whole project/solution and it keeps crashing for big js files (~100+ lines). Looks like only devenv /safemode helps to fix the problem.

**Comment by LaoR-UA** [comment] 2016-05-16 15:12
I know how to reproduce issue. Just download [this simple JS file](https://onedrive.live.com/redir?resid=88420575E46D8A6D!31924&authkey=!APn0zGSHe4eIa9A&ithint=file%2cjs), open it in VS2015 and for one minute try click at any objects method/property in file. VS2015 will crash. Sometimes in also happens on scroll up-down.
To fix that, just remove line 6: `'use strict';` and again do a 'stress-test' for 1 minute. Now it should pass.

**Comment by EdMaurer** [comment] 2016-05-16 16:09
@LaoR-UA Thanks for the repro! We'll take a look.

**Comment by mlorbetske** [comment] 2017-07-05 08:38
Since this thread hasn't been active for over a year, closing this. If anyone is still running in to this, please report the issue on the [developer community](https://developercommunity.visualstudio.com/) site

**Closed by mlorbetske** 2017-07-05 08:38 UTC
Labels: bug, Issue Tracker Notification Posted, TFS Tracked
