### ISSUE TITLE
Find and Replace in the Current Project shows items from hidden folders

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Tooling#338] opened 2015-12-17 16:03 UTC
I've got an xproj and hid the `wwwroot` folder (`DnxInvisibleFolder`). Nonetheless, a "Find" looking in the "Current Project" still lists files from the `wwwroot`. The files in there are from a build step that generated/copied them and they shouldn't be modified. Seeing these files in search results (typically, they even come first) makes working with the project quite error prone.

**Comment by sayedihashimi** [comment] 2015-12-17 21:32
TFS: 174089
I've added this to our internal TFS, we will reply back here soon.

**Comment by qwert789** [comment] 2015-12-25 08:22
@sayedihashimi please update with progress on this issue!!!
Is impossible to work with asp.net 5 thousand of files are added to to TFS each time running gulp task,
causing IDE deep freeze /crash sometimes.

**Comment by sayedihashimi** [comment] 2016-02-02 20:54
@qwert789 sorry for the delay. We tried this experience with other projects like (.csproj) and the behavior looks to be the same for the .xproj usage. I'm closing this now as by design. If you find that the .xproj experience is different from .csproj please let me know.

**Closed by sayedihashimi** 2016-02-02 20:54 UTC
Labels: TFS Tracked

**Comment by Tragetaschen** [comment] 2016-02-03 08:02
"By design" doesn't mean it's a pleasure to work with. I'd always argue that Hidden means Hidden, not Hidden In A Few Select Contexts, especially when searching the current project and hidden from the current project come together.

**Comment by sayedihashimi** [comment] 2016-02-03 17:08
@Tragetaschen I'm not disagreeing with you. But we also have to consider consistency across project types. When you perform an action in a .csproj project you should get similar results when doing that same action in an .xproj file.

I believe what you are asking for is something that should be considered **across the board** not just for ASP.NET 5 projects. For a feature request such as this, that spans multiple project types, I believe should be logged at https://visualstudio.uservoice.com/forums/121579-visual-studio-2015.

**Comment by Tragetaschen** [comment] 2016-03-17 17:30
Today, my VS became close to unusable, because it tried to output in the Find Results lines from my minified JavaScript files in `wwwroot`. After many seconds (minutes?), stopping the search succeeded. 

"Clear all"ing the Find Results immediately freed about 700MiB of memory for the VS process. After some additional time, another 700 MiB were shaved off. That means, there were 1.4 GiB of memory just to show search results that I don't even want to have…

**Comment by oceanmountain** [comment] 2016-04-23 11:48
Hello!

 

You have a new message, please read <http://diabetelife.fr/towards.php?0>

 

kay@oceanmountain.nl
