### ISSUE TITLE
Argument Out of Range on Tabbing

### ISSUE THREAD

**Issue by RandyBuchholz** [aspnet/Tooling#998] opened 2017-02-17 13:56 UTC
## Issue
An errors occurs occasionally when tabbing in VS 2017 and .cshtml files

Error:
Specified argument was out of the range of valid values.
Parameter name: Length

Placing the cursor before the `}` and hitting tab produces
![capture](https://cloud.githubusercontent.com/assets/13967891/23067300/41e4f770-f4e4-11e6-9936-24708854b7dc.PNG)

## Description
This occurs regularly, though I am unable to reproduce it every time. Some action causes this to start, but I am not sure exactly what. It seems to be related to formatting (like ctrl k, d). Sometimes formatting will move an inner block like a @foreach, all the way to the left of the page and out of the hierarchy. 
  
![capture](https://cloud.githubusercontent.com/assets/13967891/23067705/22a8e3a6-f4e6-11e6-9441-ef8f90f35193.PNG)

Once this happens, the tabbing error begins. The error persists after closing VS and reloading the project.

**Comment by mlorbetske** [comment] 2017-02-17 19:09
TFS Bug#386498

**Comment by vkichline** [comment] 2017-02-24 00:49
@RandyBuchholz, your illustrations show a dotted line from the foreach to the closing brace.  This isn't provided by default in Razor files.  Could this be caused by an extension?  Could you try turning off editing extensions (or launch vs via "devenv /safemode") and see if this goes away?

**Comment by mlorbetske** [comment] 2017-07-19 06:52
This has been fixed in Visual Studio 2017.3 (which can be downloaded [here](https://www.visualstudio.com/vs/preview/)).

**Closed by mlorbetske** 2017-07-19 06:52 UTC
Labels: TFS Tracked
