### ISSUE TITLE
DNX Errors when working with RC2 Project!

### ISSUE THREAD

**Issue by shrib** [aspnet/Tooling#528] opened 2016-05-24 21:23 UTC
Don't know how to repro this issue. I added some projects to the WebAPI solution created after installing RC2 and uninstalling prior versions of .NET Core.

I randomly got a message saying DNX version had to be installed. Screenshot here: https://slack-files.com/T0APT897D-F1BDUEB25-baded658de

The only thing that I did differently on this computer is:
a. Installed RC2 via VS Notification
b. Uninstalled ASP.NET RC1 tooling afterwards (because the VS Tooling Installation didn't do it :()

**Comment by sayedihashimi** [comment] 2016-05-26 23:22
TFS: 225802
I've added this to our internal TFS, we will reply back here soon.

**Comment by balachir** [comment] 2016-06-10 18:25
@shrib, can you consistently reproduce the issue or was it a one-time thing?

Your note in (b) above seems to indicate a possible setup issue too because RC1 should have been automatically uninstalled as part of RC2 installation. Does Add/Remove programs contain an entry for "Microsoft .NET Core 1.0.0 RC2 - VS 2015 Tooling Preview 1" and Help-About in Visual Studio contain an entry for "Microsoft .NET Core Tools (Preview 1)" ?

**Comment by shrib** [comment] 2016-06-15 14:16
It could be a setup issue.. not sure. I do see RC2/Preview 1 everywhere necessary and no traces of RC1. I have seen this popup a few times on at least 2 of my machines.

**Comment by balachir** [comment] 2016-06-16 14:00
Hmm, that's odd. Some more questions:
- If you do File > New project > ASP.NET Core web application, does it work and you get 1.0.0-preview1-002702 in global.json?
- Can you share a sample project if possible that reproduces the issue?

**Comment by mlorbetske** [comment] 2017-07-04 22:27
Since there hasn't been an update here in over a year, closing this issue. If you're still running in to this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site

**Closed by mlorbetske** 2017-07-04 22:27 UTC
Labels: TFS Tracked
