### ISSUE TITLE
restore fails in VS, but not in powershell

### ISSUE THREAD

**Issue by esargent** [aspnet/Tooling#642] opened 2016-07-01 18:43 UTC
I have an aspnetcore app project and a test project. Often, when I edit project.json the restore will fail in the test project with the error `An item with the same key has already been added. Key: MyMVCProject`

But if I drop down to powershell and run `dotnet restore` it works.

Sometimes the error message remains in the Error List window, BUT, the visual indicator in Solution Explorer resolves for the test project and I can compile successfully (which will remove the error list message if it exists.)

In this same scenario, I can re-run "restore packages" from the Visual Studio menu in Solution Explorer and continue to get the error, but dropping down to the powershell command fixes the issue.

The VS output log doesn't show any errors:
`
Retrieving package 'Newtonsoft.Json 9.0.1' from 'Microsoft and .NET'.
  GET https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/Packages(Id='Newtonsoft.Json',Version='9.0.1')
  OK https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/Packages(Id='Newtonsoft.Json',Version='9.0.1') 101ms
Installing NuGet package Newtonsoft.Json.9.0.1.
Successfully installed 'Newtonsoft.Json 9.0.1' to My.Portal.Test
Executing nuget actions took 402.06 ms
========== Finished ==========
Time Elapsed: 00:00:00.8570988
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%
C:\Program Files\dotnet\dotnet.exe restore "C:\code\MyPortalSolution\.vs\restore.dg"
log  : Restoring packages for C:\code\MyPortalSolution\tests\My.Portal.Test\project.json...
log  : Writing lock file to disk. Path: C:\code\MyPortalSolution\tests\My.Portal.Test\project.lock.json
log  : C:\code\MyPortalSolution\tests\My.Portal.Test\My.Portal.Test.xproj
log  : Restore completed in 19900ms.
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%
C:\Program Files\dotnet\dotnet.exe restore "C:\code\MyPortalSolution\.vs\restore.dg"
log  : Restoring packages for C:\code\MyPortalSolution\tests\My.Portal.Test\project.json...
log  : Writing lock file to disk. Path: C:\code\MyPortalSolution\tests\My.Portal.Test\project.lock.json
log  : C:\code\MyPortalSolution\tests\My.Portal.Test\My.Portal.Test.xproj
log  : Restore completed in 17630ms.
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%
C:\Program Files\dotnet\dotnet.exe restore "C:\code\MyPortalSolution\.vs\restore.dg"
log  : Restoring packages for C:\code\MyPortalSolution\tests\My.Portal.Test\project.json...
log  : Writing lock file to disk. Path: C:\code\MyPortalSolution\tests\My.Portal.Test\project.lock.json
log  : C:\code\MyPortalSolution\tests\My.Portal.Test\My.Portal.Test.xproj
log  : Restore completed in 10840ms.
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%
C:\Program Files\dotnet\dotnet.exe restore "C:\code\MyPortalSolution\.vs\restore.dg"
log  : Restoring packages for C:\code\MyPortalSolution\tests\My.Portal.Test\project.json...
log  : Restoring packages for C:\code\MyPortalSolution\src\MyMVC\project.json...
log  : Restoring packages for tool 'BundlerMinifier.Core' in C:\code\MyPortalSolution\src\MyMVC\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in C:\code\MyPortalSolution\src\MyMVC\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in C:\code\MyPortalSolution\src\MyMVC\project.json...
log  : Writing lock file to disk. Path: C:\code\MyPortalSolution\src\MyMVC\project.lock.json
log  : C:\code\MyPortalSolution\src\MyMVC\My.Mvc.xproj
log  : Restore completed in 18922ms.
log  : Writing lock file to disk. Path: C:\code\MyPortalSolution\tests\My.Portal.Test\project.lock.json
log  : C:\code\MyPortalSolution\tests\My.Portal.Test\My.Portal.Test.xproj
log  : Restore completed in 23571ms.
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%
C:\Program Files\dotnet\dotnet.exe restore "C:\code\MyPortalSolution\.vs\restore.dg"
log  : Restoring packages for C:\code\MyPortalSolution\src\MyMVC\project.json...
log  : Restoring packages for C:\code\MyPortalSolution\tests\My.Portal.Test\project.json...
log  : Restoring packages for tool 'BundlerMinifier.Core' in C:\code\MyPortalSolution\src\MyMVC\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in C:\code\MyPortalSolution\src\MyMVC\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in C:\code\MyPortalSolution\src\MyMVC\project.json...
log  : Writing lock file to disk. Path: C:\code\MyPortalSolution\src\MyMVC\project.lock.json
log  : C:\code\MyPortalSolution\src\MyMVC\My.Mvc.xproj
log  : Restore completed in 18746ms.
log  : Writing lock file to disk. Path: C:\code\MyPortalSolution\tests\My.Portal.Test\project.lock.json
log  : C:\code\MyPortalSolution\tests\My.Portal.Test\My.Portal.Test.xproj
log  : Restore completed in 23201ms.
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%
C:\Program Files\dotnet\dotnet.exe restore "C:\code\MyPortalSolution\.vs\restore.dg"
log  : Restoring packages for C:\code\MyPortalSolution\tests\My.Portal.Test\project.json...
log  : Restoring packages for C:\code\MyPortalSolution\src\MyMVC\project.json...
log  : Restoring packages for tool 'BundlerMinifier.Core' in C:\code\MyPortalSolution\src\MyMVC\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in C:\code\MyPortalSolution\src\MyMVC\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in C:\code\MyPortalSolution\src\MyMVC\project.json...
log  : Writing lock file to disk. Path: C:\code\MyPortalSolution\src\MyMVC\project.lock.json
log  : C:\code\MyPortalSolution\src\MyMVC\My.Mvc.xproj
log  : Restore completed in 18885ms.
log  : Writing lock file to disk. Path: C:\code\MyPortalSolution\tests\My.Portal.Test\project.lock.json
log  : C:\code\MyPortalSolution\tests\My.Portal.Test\My.Portal.Test.xproj
log  : Restore completed in 23483ms.`

If I build in VS prior to running restore in powershell, I get an error.

`1>------ Build started: Project: My.Mvc, Configuration: Debug Any CPU ------
1>Build started 7/1/2016 11:35:54 AM.
1>     1>
1>CoreCompile:
1>         C:\Program Files\dotnet\dotnet.exe build "C:\code\MyPortalSolution\src\MyMVC" --configuration Debug --no-dependencies
1>         Project MyMVC (.NETCoreApp,Version=v1.0) will be compiled because inputs were modified
1>         Compiling MyMVC for .NETCoreApp,Version=v1.0
1>         Compilation succeeded.
1>             0 Warning(s)
1>             0 Error(s)
1>         Time elapsed 00:00:04.3222995
1>
1>       GetTypeScriptCopyToOutputDirectoryItems:
1>         Adding items with BuildAction=TypeScriptCompile to the same collections that will be populated (with items of other BuildActions) by the GetCopyToOutputDirectoryItems target
1>
1>Build succeeded.
1>
1>Time Elapsed 00:00:06.89
2>------ Build started: Project: My.Portal.Test, Configuration: Debug Any CPU ------
2>Build started 7/1/2016 11:36:01 AM.
2>     1>
2>CoreCompile:
2>         C:\Program Files\dotnet\dotnet.exe build "C:\code\MyPortalSolution\tests\My.Portal.Test" --configuration Debug --no-dependencies
2>     1>
2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error : An item with the same key has already been added. Key: MyMVC
2>
2>Build FAILED.
2>
2>Time Elapsed 00:00:00.50
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

MyMVC project.json
`{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "MailKit": "1.3.0-rc1-1",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
    "Microsoft.Extensions.Caching.Memory": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0"
  },
 "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },
 "frameworks": {
  "netcoreapp1.0": {
    "imports": [
      "dotnet5.6",
      "portable-net45+win8"
    ]
  }
  },
   "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "xmlDoc": false
  },
  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },
  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },
  "version": "1.0.0-*"
}`

Test project.json
`
{
  "dependencies": {
    "MyMVC": "*",
    "Microsoft.EntityFrameworkCore.InMemory": "1.0.0",
    "xunit": "2.2.0-*",
    "xunit.runner.visualstudio": "2.2.0-*",
    "dotnet-test-xunit": "2.2.0-*",
    "System.Linq": "4.1.0"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        }
      },
      "imports": [
        "net46"
      ]
    }
  },
  "testRunner": "xunit"
}
`

**Comment by barrytang** [comment] 2016-07-06 04:26
@jinujoseph, can you take a look?

**Comment by jinujoseph** [comment] 2016-07-11 22:36
I tried to repro this with dotnet sdk version 1.0.0-preview2-003121 but was not able to.
Can you let us know whats your nuget package source set as? 

Also adding joelverhagen from nuget team

**Comment by sayedihashimi** [comment] 2016-07-11 23:04
Adding @joelverhagen

**Comment by esargent** [comment] 2016-07-12 01:00
As far as repo - I haven't been able to find a scenario today where it does NOT happen. I'm not clear what you mean by "provide the call stack" in this context of config & build, but am glad to provide if you can help with where to look.

I think you are on to something with the nuget packages -  I tried to pull up the package manager GUI in VS and I got an error "The schema version of 'Microsoft.NETCore.App' is incompatible with version 2.12.0.815 of NuGet." I don't remember seeing that before. What is strange is that Extensions & Updates shows NuGet as 3.5.0.1484.

I uninstalled and reinstalled "NuGet Package Manager for Visual Studio 2015" and now have 3.4.4.1321. Looks like I got a pre-release version somehow before. However, when I go to the GUI package manager (right-click Manage nuGet packages on project) it still gets the same error. It's not clear to me what changed between this week and last that is now causing this error, or maybe I didn't notice because the GUI still works for adds/updates to existing packages to a project, I just can't view existing.

Also, I created a brand new aspnetcore project (Web application, not hosted in azure) using the Visual Studio new project menu. That gives the same experience as above with reference to the v2.12.0.815.

My nuget sources, in order are:
https://api.nuget.org/v3/index.json
https://www.myget.org/F/aspnetvnext/
https://www.myget.org/F/xunit/api/v2/ (unchecked)
And machine wide:
https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/
C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Settings in VS options are: 
(Checked) "Allow nuget to download missing packages"
(Checked) "Automatically check for missing packages"
(unchecked) "skip applying binding redirects"

**Comment by esargent** [comment] 2016-07-12 19:39
Not sure how relevant, but:
	• I found a reference to the 3.5 version of nuget still has a reference in the registry, and was installed by NuGetVisualStudio14_rc2_39.msi, which refers to a cached package which still exists on disk. C:\ProgramData\Package Cache\{08D9540E-77B1-37B3-909A-813DAA5523D0}v3.5.0.1484\packages
	• However, the Extensions window and the Package Manage Console both now report 3.4.4.1321.

HKEY_CURRENT_USER\SOFTWARE\Microsoft\Blend\14.0_Config\InstalledProducts\NuGetPackage refers to package {5fcc8577-4feb-4d04-ad72-d6c629b083cc} and PID 3.5.0
However, if I pull up Blend and open Package Manage Console it also reports 3.4.4.1321 and I don't really use Blend.

Is it expected that HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\ExtensionManager\ExtensionAutoUpdateEnrollment  has references to all of these?
NuGet.0d421874-a3b2-4f67-b53a-ecfce878063b,3.0.60624.657
NuGet.0d421874-a3b2-4f67-b53a-ecfce878063b,3.2.60914.10516
NuGet.0d421874-a3b2-4f67-b53a-ecfce878063b,3.3.0.167
NuGet.0d421874-a3b2-4f67-b53a-ecfce878063b,3.4.1.807
NuGet.0d421874-a3b2-4f67-b53a-ecfce878063b,3.4.2.830
NuGet.0d421874-a3b2-4f67-b53a-ecfce878063b,3.4.4.1321
NuGet.0d421874-a3b2-4f67-b53a-ecfce878063b,3.5.0.1284

I didn't find any reference to 2.12 version stated in the error message

In C:\Program Files (x86)\Microsoft SDKs\NuGetPackages there are folders for 
Nuget.Common
Nuget.Configuration
Nuget.DependencyResolver.Core
And 11 more similar
Inside each folder is subfolder called "3.5.0-beta2-1484" with nupkg and nuspec and sha512 files inside. Not sure if that is the expected naming because of the tools release, but seems strange the discrepancy between the 3.4.x and 3.5.x versioning.

not sure if any of this is helpful, but it seems off

**Comment by esargent** [comment] 2016-07-12 20:02
I have just figured out one part of the repo puzzle. If I delete project.lock.json in the Test project, it will restore packages and be successful, just like doing it from the powershell. 
But if I just right-click "restore packages" from the VS GUI, it fails repeatedly.

I really seems like some sort of caching issue because one packages are restored properly I can build repeatedly and do everything I need to do until I mess with the packages again.

**Comment by joelverhagen** [comment] 2016-07-12 20:29
Concerning the following error: `The schema version of 'Microsoft.NETCore.App' is incompatible with version 2.12.0.815 of NuGet.`

This is likely occurring due to a bad package being in your cache. I was able to reproduce this error by restoring this package:
https://www.myget.org/feed/aspnetcidev/package/nuget/Microsoft.NETCore.App/1.0.0-rc3-004443-00

Go ahead and clear your package cache (`nuget.exe locals -clear all`).

**Comment by esargent** [comment] 2016-07-12 22:07
@joelverhagen  - yes, that fixed the issue with the package manager GUI.

No change to the other restore symptoms.

**Comment by jinujoseph** [comment] 2016-07-12 22:33
whats the other restore symptoms ? 
Are you referring to  error : An item with the same key has already been added ? If so can you tell us the repro steps , as in what do you change in the project.json which triggers this ?

**Comment by esargent** [comment] 2016-07-12 23:08
Yes, the "An item with the same key has already been added" error on build with the dependent Test project.

I read your note above that you weren't able to repo, but for me changing anything in "dependencies" or "frameworks" section, which triggers a package restore operation, will trigger the issue for me. I can make changes to areas of project.json like "build options" without issue.

Specifically, I can add or remove any arbitrary package from dependencies, or change the framework or imports to any arbitrary valid value as far as I can tell. I've tried adding both Microsoft and 3rd party packages. I've tried getting rid of all the RC2 tools as dependencies. It doesn't seem to matter what changes, what is important is that the package restore is triggered in the main project and then the Test project isn't able to handle that change.

What I also noticed is that once the issue occurs and the yellow error icon is showing on the Test References icon, is that if I make other changes to project.json in the main project - changes that don't trigger package restore and wouldn't cause the problem to occur - it causes the icon on the Test project to blink back to normal and then back to the error within a second, but it is like it is evaluating something. So, specifically what I mean is that I could (in the main MVC project) change "buildOptions":"emitEntryPoint" from true to false and save. That will trigger the blink in the Test project. And then I can change it back from false to true, save, and observe the blink again. Same thing is true for "runtimeOptions": "configProperties": "System.GC.Server" for instance.

This is a new problem with the new tooling. I've been manually editing project.json since RC1 without any issues.

**Comment by mlorbetske** [comment] 2016-07-18 18:38
TFS Bug#241365

**Comment by mlorbetske** [comment] 2016-07-28 20:40
+ @abpiskunov

**Comment by mlorbetske** [comment] 2017-01-04 09:08
These problems should be resolved with the .NET Core tooling for Visual Studio 2017

**Closed by mlorbetske** 2017-01-04 09:08 UTC
Labels: TFS Tracked
