### ISSUE TITLE
Azure App Service fails to publisn .net core RTM app

### ISSUE THREAD

**Issue by johnkwaters** [aspnet/Tooling#654] opened 2016-07-06 05:31 UTC
I have a project that is a .net core WebAPI project, that uses two .net core class libraries. In RC2 the auto publish feature worked whenever I check in to VSTS Git, but in the RTM, it fails, trying to publish one of the class libraries!

D:\Program Files (x86)\dotnet\dotnet.exe publish "D:\home\site\repository\src\PC.Model" --output "D:\local\Temp\PublishTemp\PC.Model51" --configuration Release --no-build
D:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): error : Can not find runtime target for framework '.NETStandard,Version=v1.6' compatible with one of the target runtimes: 'win8-x86, win7-x86'. Possible causes: [D:\home\site\repository\src\PC.Model\PC.Model.xproj]
D:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): error : 1. The project has not been restored or restore failed - run `dotnet restore` [D:\home\site\repository\src\PC.Model\PC.Model.xproj]
D:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): error : 2. The project does not list one of 'win8-x86, win7-x86' in the 'runtimes' section. [D:\home\site\repository\src\PC.Model\PC.Model.xproj]
D:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): error : 3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries. [D:\home\site\repository\src\PC.Model\PC.Model.xproj]

**Comment by mlorbetske** [comment] 2016-07-18 18:38
TFS Bug#241371

**Comment by mlorbetske** [comment] 2016-07-19 15:49
@johnkwaters does this work if you publish from VS? Trying to narrow down where the issue is

**Comment by johnkwaters** [comment] 2016-07-19 16:21
Yes, that works, and that is how I do it for now.

Xcopy deploy from the files published to the file system is another option

When the portal builds, you cannot specify which project to build, and it seems to choose to build one of the .net core assemblies in the solution as the primary project, instead of the correct one.

Hope that helps.

 

John Waters, MVP

CTO4Hire LLC

c: 831.295.3218

 <http://www.cto4hire.net> www.cto4hire.net

**Comment by mlorbetske** [comment] 2017-07-04 23:45
Sorry for the lack of updates, linked TFS item was sent to the folks who work on the portal. Since it's been quite a while, without any further updates here, I'll close this item. If you're still running in to this issue, please report it on the [developer community](https://developercommunity.visualstudio.com/) site.

**Closed by mlorbetske** 2017-07-04 23:45 UTC
Labels: TFS Tracked
