### ISSUE TITLE
Unable to locate Microsoft.CodeAnalysis.CSharp >= 2.0.0-beta1-20150806-01

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Tooling#154] opened 2015-08-19 23:49 UTC
Update to Latest dev version(v1.0.0-beta7-15019) produce this error.
Where is the  Microsoft.CodeAnalysis.CSharp >= 2.0.0-beta1-20150806-01?
Is it moved to another feed?

 `dnu restore` has the same result.
Thanks

**Comment by per-samuelsson** [comment] 2015-08-20 08:00
If you post the same issue in different repos, I suggest you at least cross-reference them. Consider the administrative pain for the DNX team. This is a duplicate of https://github.com/aspnet/dnx/issues/2517, isn't it?

**Comment by davidfowl** [comment] 2015-08-20 08:08
Closing this one.

**Closed by davidfowl** 2015-08-20 08:08 UTC

**Comment by mikeandersun** [comment] 2015-08-20 08:14
Yes. Sorry. 
How can delete it?
