### ISSUE TITLE
Visual Studio 2015  IIS Express 10 hangs when running an ASP.NET Core 1.0 RTM app

### ISSUE THREAD

**Issue by MaherJendoubi** [aspnet/Tooling#682] opened 2016-07-22 18:17 UTC
Failed to start process with commandline '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\ProjectSystem\VSIISExeLauncher.exe" -debug -p "C:\Program Files\dotnet\dotnet.exe" -a "C:\Users\XXXX\documents\visual studio 2015\Projects\WebApplication1\src\WebApplication1\bin\Debug\netcoreapp1.0\WebApplication1.dll" -pidFile "C:\Users\XXXX\AppData\Local\Temp\tmp6734.tmp" -wd "C:\Users\XXXX\documents\visual studio 2015\Projects\WebApplication1\src\WebApplication1"', ErrorCode = '0x80004005'.

**Comment by GuardRex** [comment] 2016-07-22 18:28
That error code can occur when the RID bitness doesn't match the platform bitness (e.g. working with x64 tooling but try to publish an x86 app).

**Comment by MaherJendoubi** [comment] 2016-07-22 18:45
@GuardRex I used the following tooling https://www.microsoft.com/net/core#windows

**Comment by wpostma** [comment] 2016-07-25 13:40
I think you must be using a 64 bit version of Windows, and IIS Express is 32 bit, but perhaps you can give a reproducible case that other people could try, if you gave enough additional information, including whatever is relevant to reproduce the issue.

**Comment by MaherJendoubi** [comment] 2016-07-25 13:56
@wpostma In deed, I have a 64 bit version of Windows. I uninstalled IIS 10 Express and installed 64 bit version but in vain... Have you please the right links for downloading IIS?

**Comment by MaherJendoubi** [comment] 2016-07-25 14:00
![image](https://cloud.githubusercontent.com/assets/1798510/17103913/dfc83b66-5280-11e6-9e8c-dc8230e88a13.png)

**Comment by wpostma** [comment] 2016-07-25 17:24
I have no such problem here. I have Visual Studio 2015 and all updates, and do not see issue like you post. That's why I asked you to check if it's reproducible. Create a new project, and see if this happens.
Then add stuff from your other project's project.json, and so on.

**Comment by MaherJendoubi** [comment] 2016-07-25 17:25
@wpostma The problem remains.

**Comment by wpostma** [comment] 2016-07-25 17:27
Unless you can describe the steps to reproduce this bug, nobody can help you.

**Comment by MaherJendoubi** [comment] 2016-07-25 17:30
@wpostma when I do create new project asp.net core and I do F5, this bug happens. Which data I could share to reproduce this bug or analyze it, please?

**Comment by wpostma** [comment] 2016-07-25 17:32
Do you have any other computer you can try this on?  Do you have ALL Visual Studio Update 3 and all post update3 hotfixes?    What dotnet version is in dotnet --version? 1.0.0-preview2-003121 or other?

**Comment by wpostma** [comment] 2016-07-25 17:34
Also try creating your project in c:\work, instead of in the default location.

**Comment by MaherJendoubi** [comment] 2016-07-25 17:35
I have only one pc. I installed all VS Update 3 and all post update 3 hotfixes. dotnet --version gives 1.0.0-preview2-003121.

**Comment by MaherJendoubi** [comment] 2016-07-25 17:39
@wpostma same result and in the output console I have : 
Le programme '[10404] dotnet.exe' s'est arrêté avec le code -2147450751 (0x80008081).
Le programme '[9808] iisexpress.exe' s'est arrêté avec le code 0 (0x0).

**Comment by wpostma** [comment] 2016-07-25 17:42
In command prompt, Run "systeminfo >c:\sysinfo.txt" and post your system information (sysinfo.txt)

**Comment by MaherJendoubi** [comment] 2016-07-25 17:47
[sysinfo.txt](https://github.com/aspnet/Tooling/files/382112/sysinfo.txt)

**Comment by wpostma** [comment] 2016-07-25 17:47
I have never uninstalled or reinstalled IIS Express. I always have used the version that was installed for me with Visual Studio.

**Comment by wpostma** [comment] 2016-07-25 17:56
I wonder if there is a non-english locale bug in the dotnet preview tooling.

**Comment by MaherJendoubi** [comment] 2016-07-25 17:58
don't tell me to uninstall VS one more time :(

**Comment by wpostma** [comment] 2016-07-25 17:59
I'm just a regular developer like you. But I suspect you will get your system working sooner if you do a clean install.

**Comment by MaherJendoubi** [comment] 2016-07-25 18:00
@wpostma Thanks

**Comment by mlorbetske** [comment] 2016-07-25 18:33
TFS Bug#243979

**Comment by mlorbetske** [comment] 2016-07-26 20:42
@MaherJendoubi can you select the debug target that's just your application name from the debug dropdown on the toolbar please? This will run your app through the self host server. Could you share whether you experience a similar error doing it this way?

**Comment by MaherJendoubi** [comment] 2016-07-26 20:46
@mlorbetske I'm sorry I'm blocked because I unistalled VS, reinstalled and I get this big problem now : 
![image](https://cloud.githubusercontent.com/assets/1798510/17154789/c6de13e8-5382-11e6-85ed-4248ec749fa0.png)

**Comment by MaherJendoubi** [comment] 2016-07-26 20:50
@mlorbetske I share the logs here https://gist.github.com/MaherJendoubi/975cbca78779ae7653688edec86e6df4

**Comment by mlorbetske** [comment] 2016-07-26 21:01
Hi @MaherJendoubi could you try running the installer at the command line with "DotNetCore.1.0.0-VS2015Tools.Preview2.exe SKIP_VSU_CHECK=1"

**Comment by MaherJendoubi** [comment] 2016-07-26 21:19
![image](https://cloud.githubusercontent.com/assets/1798510/17155922/6f9a5b64-5387-11e6-9413-3b01bbca11d1.png)

**Comment by mlorbetske** [comment] 2016-07-26 21:27
@MaherJendoubi Does install complete successfully when you click install after launching the installer in this way?

**Comment by MaherJendoubi** [comment] 2016-07-26 21:31
![image](https://cloud.githubusercontent.com/assets/1798510/17156240/14aba562-5389-11e6-9cca-50c1c4fc0e92.png)

**Comment by MaherJendoubi** [comment] 2016-07-26 21:32
@mlorbetske it takes a while for the install...I'm testing...

**Comment by MaherJendoubi** [comment] 2016-07-26 21:41
@mlorbetske all the templates are working like a charm now. So the problem is in the French version of Visual Studio when installing the asp.net core tooling... Thanks a lot for the great help!

**Comment by mlorbetske** [comment] 2016-07-28 20:25
@MaherJendoubi do you mean the installation issue or the original issue you posted about is a problem with the French version of VS?

**Comment by MaherJendoubi** [comment] 2016-07-28 21:25
@mlorbetske yes

**Comment by mlorbetske** [comment] 2016-07-28 21:46
@MaherJendoubi which one?

**Comment by BrainCrumbz** [comment] 2016-08-16 00:19
@MaherJendoubi not sure is completely solved for you now or what, but for future readers: I see the same error message in *Windows event viewer\Windows logs\Application* with same error code, but just before that error there's a warning with message similar to:

> The directory specified for caching compressed content C:\Users\myname\AppData\Local\Temp\iisexpress\IIS Temporary Compressed Files\Clr4IntegratedAppPool is invalid.  Static compression is being disable

The error seems to be the final consequence, but root cause could be identified from that warning. This issue #309 seems a possible explanation for such a warning.

**Comment by hfmanson** [comment] 2016-10-02 09:38
At my VS 2015 configuration C:\Users\myname\AppData\Local\Temp\iisexpress did not contain any subdirectories. After manually creating IIS Temporary Compressed Files\Clr4IntegratedAppPool directories no more events occur and IIS Express no longer hangs

**Comment by mlorbetske** [comment] 2017-01-04 09:06
Closing this as the original issue seems to be resolved

**Closed by mlorbetske** 2017-01-04 09:06 UTC
Labels: TFS Tracked
