### ISSUE TITLE
Nesting issue in RC2 Build

### ISSUE THREAD

**Issue by scottsauber** [aspnet/Tooling#454] opened 2016-04-20 12:39 UTC
I like to structure the folders of my code by feature/module, rather than technology.  I don't like bouncing around between different folders like controllers, view models, views, etc. when on big projects.

I'm getting nesting issues while using Visual Studio and the RC2 Build that I got from the DevIntersection ASP.NET Core workshop with Damian and Glenn.  It's not looking at the extension for nesting, it just nests items with the same name.  To me, that seems wrong unless I'm not thinking of a certain scenario.

I tried this with the ASP.NET 4.x VS tooling and I do not have this problem.

Here's a screenshot:
![](https://i.imgur.com/NPx8LdJ.png)

Let me know if you need more info.  Thanks.

**Comment by sayedihashimi** [comment] 2016-04-26 17:10
Hi @scottsauber thanks for the note. This is a duplicate of https://github.com/aspnet/Tooling/issues/347. Closing this one.

**Closed by sayedihashimi** 2016-04-26 17:10 UTC
